#nullable enable
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
namespace Wahren.AbstractSyntaxTree.Node;
public partial struct VoiceNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<StringArrayElement> voice_type = new();
	public VariantPair<StringArrayElement> delskill = new();
	public VariantPair<StringArrayElement> spot = new();
	public VariantPair<StringArrayElement> roam = new();
	public VariantPair<StringArrayElement> power = new();

	public void Dispose()
	{
		voice_type.Dispose();
		delskill.Dispose();
		spot.Dispose();
		roam.Dispose();
		power.Dispose();
	}
}
public partial struct SpotNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> value = new();
	public VariantPair<Pair_NullableString_NullableIntElement> politics = new();
	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> x = new();
	public VariantPair<Pair_NullableString_NullableIntElement> y = new();
	public VariantPair<Pair_NullableString_NullableIntElement> w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> big = new();
	public VariantPair<Pair_NullableString_NullableIntElement> map = new();
	public VariantPair<Pair_NullableString_NullableIntElement> castle_battle = new();
	public VariantPair<Pair_NullableString_NullableIntElement> limit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bgm = new();
	public VariantPair<Pair_NullableString_NullableIntElement> volume = new();
	public VariantPair<Pair_NullableString_NullableIntElement> gain = new();
	public VariantPair<Pair_NullableString_NullableIntElement> castle = new();
	public VariantPair<Pair_NullableString_NullableIntElement> capacity = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dungeon = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_home = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_raise = new();
	public VariantPair<Pair_NullableString_NullableIntElement> castle_lot = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> merce = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> monster = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> yorozu = new();
	public VariantPair<StringElement> text = new();

	public void Dispose()
	{
		value.Dispose();
		politics.Dispose();
		name.Dispose();
		image.Dispose();
		x.Dispose();
		y.Dispose();
		w.Dispose();
		h.Dispose();
		big.Dispose();
		map.Dispose();
		castle_battle.Dispose();
		limit.Dispose();
		bgm.Dispose();
		volume.Dispose();
		gain.Dispose();
		castle.Dispose();
		capacity.Dispose();
		dungeon.Dispose();
		no_home.Dispose();
		no_raise.Dispose();
		castle_lot.Dispose();
		merce.Dispose();
		monster.Dispose();
		member.Dispose();
		yorozu.Dispose();
		text.Dispose();
	}
}
public partial struct UnitNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> troop_sort = new();
	public VariantPair<Pair_NullableString_NullableIntElement> stealth = new();
	public VariantPair<Pair_NullableString_NullableIntElement> free_move = new();
	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> help = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sex = new();
	public VariantPair<Pair_NullableString_NullableIntElement> a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sub_image_even = new();
	public VariantPair<Pair_NullableString_NullableIntElement> radius = new();
	public VariantPair<Pair_NullableString_NullableIntElement> radius_press = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_escape = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_regular = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_knock = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_cover = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dead_event = new();
	public VariantPair<Pair_NullableString_NullableIntElement> beast_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> summon_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> summon_level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> escape_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> escape_run = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hand_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> wake_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> view_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> cavalry_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> view_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_view_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_blind_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> satellite = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hasexp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defense = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magic = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdef = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dext = new();
	public VariantPair<Pair_NullableString_NullableIntElement> move = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprec = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprec = new();
	public VariantPair<Pair_NullableString_NullableIntElement> heal_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defense_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magic_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdef_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speed_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dext_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> move_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprec_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprec_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> movetype = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hpUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mpUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attackUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defenseUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magicUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdefUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speedUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dextUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> moveUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprecUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprecUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hpMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mpMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attackMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defenseMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magicMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdefMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speedMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dextMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> moveMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprecMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprecMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> race = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sortkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_atmark_cutin = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_detail = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_menu = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_floor = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_shift = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_shift_up = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_center = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_back = new();
	public VariantPair<Pair_NullableString_NullableIntElement> price = new();
	public VariantPair<Pair_NullableString_NullableIntElement> cost = new();
	public VariantPair<Pair_NullableString_NullableIntElement> finance = new();
	public VariantPair<Pair_NullableString_NullableIntElement> tkool = new();
	public VariantPair<Pair_NullableString_NullableIntElement> keep_form = new();
	public VariantPair<Pair_NullableString_NullableIntElement> breast_width = new();
	public VariantPair<Pair_NullableString_NullableIntElement> medical = new();
	public VariantPair<Pair_NullableString_NullableIntElement> active = new();
	public VariantPair<Pair_NullableString_NullableIntElement> handle = new();
	public VariantPair<Pair_NullableString_NullableIntElement> red = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rank_text = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_training = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_voice = new();
	public VariantPair<Pair_NullableString_NullableIntElement> face = new();
	public VariantPair<Pair_NullableString_NullableIntElement> same_friend = new();
	public VariantPair<Pair_NullableString_NullableIntElement> same_call = new();
	public VariantPair<Pair_NullableString_NullableIntElement> level_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp_mul = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> line = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sub_image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> politics = new();
	public VariantPair<Pair_NullableString_NullableIntElement> element_lost = new();
	public VariantPair<Pair_NullableString_NullableIntElement> lost_corpse = new();
	public VariantPair<Pair_NullableString_NullableIntElement> add_vassal = new();
	public VariantPair<Pair_NullableString_NullableIntElement> value = new();
	public VariantPair<Pair_NullableString_NullableIntElement> @break = new();
	public VariantPair<Pair_NullableString_NullableIntElement> scream = new();
	public VariantPair<Pair_NullableString_NullableIntElement> talent = new();
	public VariantPair<Pair_NullableString_NullableIntElement> @class = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bgm = new();
	public VariantPair<Pair_NullableString_NullableIntElement> volume = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alive_per = new();
	public VariantPair<Pair_NullableString_NullableIntElement> yabo = new();
	public VariantPair<Pair_NullableString_NullableIntElement> kosen = new();
	public VariantPair<Pair_NullableString_NullableIntElement> align = new();
	public VariantPair<Pair_NullableString_NullableIntElement> power_name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> flag = new();
	public VariantPair<Pair_NullableString_NullableIntElement> diplomacy = new();
	public VariantPair<Pair_NullableString_NullableIntElement> actor = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable_select = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> fix = new();
	public VariantPair<Pair_NullableString_NullableIntElement> noremove_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> noemploy_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> noitem_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> arbeit_capacity = new();
	public VariantPair<Pair_NullableString_NullableIntElement> join = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dead = new();
	public VariantPair<Pair_NullableString_NullableIntElement> retreat = new();
	public VariantPair<Pair_NullableString_NullableIntElement> brave = new();
	public VariantPair<Pair_NullableString_NullableIntElement> fkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> loyal = new();
	public VariantPair<Pair_NullableString_NullableIntElement> arbeit = new();
	public VariantPair<StringElement> text = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> yorozu = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> consti = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> leader_skill = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> assist_skill = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> activenum = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> multi = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> skill = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> skill2 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> learn = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> home = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> merce = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> item = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> castle_guard = new();
	public VariantPair<StringArrayElement> friend = new();
	public VariantPair<StringArrayElement> delskill = new();
	public VariantPair<StringArrayElement> delskill2 = new();
	public VariantPair<StringArrayElement> enemy = new();
	public VariantPair<StringArrayElement> staff = new();
	public VariantPair<StringArrayElement> voice_type = new();

	public void Dispose()
	{
		troop_sort.Dispose();
		stealth.Dispose();
		free_move.Dispose();
		name.Dispose();
		help.Dispose();
		sex.Dispose();
		a.Dispose();
		h.Dispose();
		w.Dispose();
		sub_image_even.Dispose();
		radius.Dispose();
		radius_press.Dispose();
		no_escape.Dispose();
		no_regular.Dispose();
		no_knock.Dispose();
		no_cover.Dispose();
		dead_event.Dispose();
		beast_unit.Dispose();
		summon_max.Dispose();
		summon_level.Dispose();
		attack_range.Dispose();
		escape_range.Dispose();
		escape_run.Dispose();
		hand_range.Dispose();
		wake_range.Dispose();
		view_range.Dispose();
		cavalry_range.Dispose();
		view_unit.Dispose();
		force_view_unit.Dispose();
		force_blind_unit.Dispose();
		satellite.Dispose();
		hasexp.Dispose();
		level.Dispose();
		hp.Dispose();
		mp.Dispose();
		attack.Dispose();
		defense.Dispose();
		magic.Dispose();
		magdef.Dispose();
		speed.Dispose();
		dext.Dispose();
		move.Dispose();
		hprec.Dispose();
		mprec.Dispose();
		heal_max.Dispose();
		attack_max.Dispose();
		defense_max.Dispose();
		magic_max.Dispose();
		magdef_max.Dispose();
		speed_max.Dispose();
		dext_max.Dispose();
		move_max.Dispose();
		hprec_max.Dispose();
		mprec_max.Dispose();
		movetype.Dispose();
		hpUp.Dispose();
		mpUp.Dispose();
		attackUp.Dispose();
		defenseUp.Dispose();
		magicUp.Dispose();
		magdefUp.Dispose();
		speedUp.Dispose();
		dextUp.Dispose();
		moveUp.Dispose();
		hprecUp.Dispose();
		mprecUp.Dispose();
		hpMax.Dispose();
		mpMax.Dispose();
		attackMax.Dispose();
		defenseMax.Dispose();
		magicMax.Dispose();
		magdefMax.Dispose();
		speedMax.Dispose();
		dextMax.Dispose();
		moveMax.Dispose();
		hprecMax.Dispose();
		mprecMax.Dispose();
		race.Dispose();
		sortkey.Dispose();
		picture.Dispose();
		picture_atmark_cutin.Dispose();
		picture_detail.Dispose();
		picture_menu.Dispose();
		picture_floor.Dispose();
		picture_shift.Dispose();
		picture_shift_up.Dispose();
		picture_center.Dispose();
		picture_back.Dispose();
		price.Dispose();
		cost.Dispose();
		finance.Dispose();
		tkool.Dispose();
		keep_form.Dispose();
		breast_width.Dispose();
		medical.Dispose();
		active.Dispose();
		handle.Dispose();
		red.Dispose();
		rank_text.Dispose();
		no_training.Dispose();
		force_voice.Dispose();
		face.Dispose();
		same_friend.Dispose();
		same_call.Dispose();
		level_max.Dispose();
		exp.Dispose();
		exp_mul.Dispose();
		exp_max.Dispose();
		line.Dispose();
		image.Dispose();
		sub_image.Dispose();
		politics.Dispose();
		element_lost.Dispose();
		lost_corpse.Dispose();
		add_vassal.Dispose();
		value.Dispose();
		@break.Dispose();
		scream.Dispose();
		talent.Dispose();
		@class.Dispose();
		bgm.Dispose();
		volume.Dispose();
		alive_per.Dispose();
		yabo.Dispose();
		kosen.Dispose();
		align.Dispose();
		power_name.Dispose();
		flag.Dispose();
		diplomacy.Dispose();
		actor.Dispose();
		enable.Dispose();
		enable_select.Dispose();
		enable_max.Dispose();
		fix.Dispose();
		noremove_unit.Dispose();
		noemploy_unit.Dispose();
		noitem_unit.Dispose();
		arbeit_capacity.Dispose();
		join.Dispose();
		dead.Dispose();
		retreat.Dispose();
		brave.Dispose();
		fkey.Dispose();
		loyal.Dispose();
		arbeit.Dispose();
		text.Dispose();
		yorozu.Dispose();
		consti.Dispose();
		leader_skill.Dispose();
		assist_skill.Dispose();
		activenum.Dispose();
		multi.Dispose();
		skill.Dispose();
		skill2.Dispose();
		learn.Dispose();
		home.Dispose();
		member.Dispose();
		merce.Dispose();
		item.Dispose();
		castle_guard.Dispose();
		friend.Dispose();
		delskill.Dispose();
		delskill2.Dispose();
		enemy.Dispose();
		staff.Dispose();
		voice_type.Dispose();
	}
}
public partial struct RaceNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> align = new();
	public VariantPair<Pair_NullableString_NullableIntElement> movetype = new();
	public VariantPair<Pair_NullableString_NullableIntElement> brave = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> consti = new();

	public void Dispose()
	{
		name.Dispose();
		align.Dispose();
		movetype.Dispose();
		brave.Dispose();
		consti.Dispose();
	}
}
public partial struct ClassNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> troop_sort = new();
	public VariantPair<Pair_NullableString_NullableIntElement> stealth = new();
	public VariantPair<Pair_NullableString_NullableIntElement> free_move = new();
	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> help = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sex = new();
	public VariantPair<Pair_NullableString_NullableIntElement> a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sub_image_even = new();
	public VariantPair<Pair_NullableString_NullableIntElement> radius = new();
	public VariantPair<Pair_NullableString_NullableIntElement> radius_press = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_escape = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_regular = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_knock = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_cover = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dead_event = new();
	public VariantPair<Pair_NullableString_NullableIntElement> beast_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> summon_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> summon_level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> escape_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> escape_run = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hand_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> wake_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> view_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> cavalry_range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> view_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_view_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_blind_unit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> satellite = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hasexp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defense = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magic = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdef = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dext = new();
	public VariantPair<Pair_NullableString_NullableIntElement> move = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprec = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprec = new();
	public VariantPair<Pair_NullableString_NullableIntElement> heal_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defense_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magic_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdef_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speed_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dext_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> move_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprec_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprec_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> movetype = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hpUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mpUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attackUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defenseUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magicUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdefUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speedUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dextUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> moveUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprecUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprecUp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hpMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mpMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attackMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> defenseMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magicMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> magdefMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speedMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> dextMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> moveMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hprecMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mprecMax = new();
	public VariantPair<Pair_NullableString_NullableIntElement> race = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sortkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_atmark_cutin = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_detail = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_menu = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_floor = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_shift = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_shift_up = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_center = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture_back = new();
	public VariantPair<Pair_NullableString_NullableIntElement> price = new();
	public VariantPair<Pair_NullableString_NullableIntElement> cost = new();
	public VariantPair<Pair_NullableString_NullableIntElement> finance = new();
	public VariantPair<Pair_NullableString_NullableIntElement> tkool = new();
	public VariantPair<Pair_NullableString_NullableIntElement> keep_form = new();
	public VariantPair<Pair_NullableString_NullableIntElement> breast_width = new();
	public VariantPair<Pair_NullableString_NullableIntElement> medical = new();
	public VariantPair<Pair_NullableString_NullableIntElement> active = new();
	public VariantPair<Pair_NullableString_NullableIntElement> handle = new();
	public VariantPair<Pair_NullableString_NullableIntElement> red = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rank_text = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_training = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_voice = new();
	public VariantPair<Pair_NullableString_NullableIntElement> face = new();
	public VariantPair<Pair_NullableString_NullableIntElement> same_friend = new();
	public VariantPair<Pair_NullableString_NullableIntElement> same_call = new();
	public VariantPair<Pair_NullableString_NullableIntElement> level_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp_mul = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> line = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sub_image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> politics = new();
	public VariantPair<Pair_NullableString_NullableIntElement> element_lost = new();
	public VariantPair<Pair_NullableString_NullableIntElement> lost_corpse = new();
	public VariantPair<Pair_NullableString_NullableIntElement> add_vassal = new();
	public VariantPair<Pair_NullableString_NullableIntElement> value = new();
	public VariantPair<Pair_NullableString_NullableIntElement> @break = new();
	public VariantPair<Pair_NullableString_NullableIntElement> scream = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sub_image2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> unique = new();
	public VariantPair<Pair_NullableString_NullableIntElement> same_sex = new();
	public VariantPair<Pair_NullableString_NullableIntElement> brave = new();
	public VariantPair<Pair_NullableString_NullableIntElement> fkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> change = new();
	public VariantPair<StringElement> text = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> yorozu = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> consti = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> activenum = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> multi = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> skill = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> skill2 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> learn = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> friend_ex = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> merce = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> item = new();
	public VariantPair<StringArrayElement> friend = new();
	public VariantPair<StringArrayElement> delskill = new();
	public VariantPair<StringArrayElement> delskill2 = new();

	public void Dispose()
	{
		troop_sort.Dispose();
		stealth.Dispose();
		free_move.Dispose();
		name.Dispose();
		help.Dispose();
		sex.Dispose();
		a.Dispose();
		h.Dispose();
		w.Dispose();
		sub_image_even.Dispose();
		radius.Dispose();
		radius_press.Dispose();
		no_escape.Dispose();
		no_regular.Dispose();
		no_knock.Dispose();
		no_cover.Dispose();
		dead_event.Dispose();
		beast_unit.Dispose();
		summon_max.Dispose();
		summon_level.Dispose();
		attack_range.Dispose();
		escape_range.Dispose();
		escape_run.Dispose();
		hand_range.Dispose();
		wake_range.Dispose();
		view_range.Dispose();
		cavalry_range.Dispose();
		view_unit.Dispose();
		force_view_unit.Dispose();
		force_blind_unit.Dispose();
		satellite.Dispose();
		hasexp.Dispose();
		level.Dispose();
		hp.Dispose();
		mp.Dispose();
		attack.Dispose();
		defense.Dispose();
		magic.Dispose();
		magdef.Dispose();
		speed.Dispose();
		dext.Dispose();
		move.Dispose();
		hprec.Dispose();
		mprec.Dispose();
		heal_max.Dispose();
		attack_max.Dispose();
		defense_max.Dispose();
		magic_max.Dispose();
		magdef_max.Dispose();
		speed_max.Dispose();
		dext_max.Dispose();
		move_max.Dispose();
		hprec_max.Dispose();
		mprec_max.Dispose();
		movetype.Dispose();
		hpUp.Dispose();
		mpUp.Dispose();
		attackUp.Dispose();
		defenseUp.Dispose();
		magicUp.Dispose();
		magdefUp.Dispose();
		speedUp.Dispose();
		dextUp.Dispose();
		moveUp.Dispose();
		hprecUp.Dispose();
		mprecUp.Dispose();
		hpMax.Dispose();
		mpMax.Dispose();
		attackMax.Dispose();
		defenseMax.Dispose();
		magicMax.Dispose();
		magdefMax.Dispose();
		speedMax.Dispose();
		dextMax.Dispose();
		moveMax.Dispose();
		hprecMax.Dispose();
		mprecMax.Dispose();
		race.Dispose();
		sortkey.Dispose();
		picture.Dispose();
		picture_atmark_cutin.Dispose();
		picture_detail.Dispose();
		picture_menu.Dispose();
		picture_floor.Dispose();
		picture_shift.Dispose();
		picture_shift_up.Dispose();
		picture_center.Dispose();
		picture_back.Dispose();
		price.Dispose();
		cost.Dispose();
		finance.Dispose();
		tkool.Dispose();
		keep_form.Dispose();
		breast_width.Dispose();
		medical.Dispose();
		active.Dispose();
		handle.Dispose();
		red.Dispose();
		rank_text.Dispose();
		no_training.Dispose();
		force_voice.Dispose();
		face.Dispose();
		same_friend.Dispose();
		same_call.Dispose();
		level_max.Dispose();
		exp.Dispose();
		exp_mul.Dispose();
		exp_max.Dispose();
		line.Dispose();
		image.Dispose();
		sub_image.Dispose();
		politics.Dispose();
		element_lost.Dispose();
		lost_corpse.Dispose();
		add_vassal.Dispose();
		value.Dispose();
		@break.Dispose();
		scream.Dispose();
		image2.Dispose();
		sub_image2.Dispose();
		unique.Dispose();
		same_sex.Dispose();
		brave.Dispose();
		fkey.Dispose();
		change.Dispose();
		text.Dispose();
		yorozu.Dispose();
		consti.Dispose();
		activenum.Dispose();
		multi.Dispose();
		skill.Dispose();
		skill2.Dispose();
		learn.Dispose();
		friend_ex.Dispose();
		member.Dispose();
		merce.Dispose();
		item.Dispose();
		friend.Dispose();
		delskill.Dispose();
		delskill2.Dispose();
	}
}
public partial struct FieldNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> type = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attr = new();
	public VariantPair<Pair_NullableString_NullableIntElement> id = new();
	public VariantPair<Pair_NullableString_NullableIntElement> edge = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alt = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alt_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> smooth = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> color = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> joint = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> add2 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();

	public void Dispose()
	{
		type.Dispose();
		attr.Dispose();
		id.Dispose();
		edge.Dispose();
		image.Dispose();
		alt.Dispose();
		alt_max.Dispose();
		smooth.Dispose();
		color.Dispose();
		joint.Dispose();
		add2.Dispose();
		member.Dispose();
	}
}
public partial struct SkillNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> force_ray = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bright = new();
	public VariantPair<Pair_NullableString_NullableIntElement> func = new();
	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> sortkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> special = new();
	public VariantPair<Pair_NullableString_NullableIntElement> delay = new();
	public VariantPair<Pair_NullableString_NullableIntElement> quickreload = new();
	public VariantPair<Pair_NullableString_NullableIntElement> help = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hide_help = new();
	public VariantPair<Pair_NullableString_NullableIntElement> msg = new();
	public VariantPair<Pair_NullableString_NullableIntElement> picture = new();
	public VariantPair<Pair_NullableString_NullableIntElement> value = new();
	public VariantPair<Pair_NullableString_NullableIntElement> talent = new();
	public VariantPair<Pair_NullableString_NullableIntElement> exp_per = new();
	public VariantPair<Pair_NullableString_NullableIntElement> movetype = new();
	public VariantPair<Pair_NullableString_NullableIntElement> type = new();
	public VariantPair<Pair_NullableString_NullableIntElement> w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> mp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alpha_tip = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alpha_butt = new();
	public VariantPair<Pair_NullableString_NullableIntElement> anime = new();
	public VariantPair<Pair_NullableString_NullableIntElement> anime_interval = new();
	public VariantPair<Pair_NullableString_NullableIntElement> center = new();
	public VariantPair<Pair_NullableString_NullableIntElement> d360 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> d360_adj = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rotate = new();
	public VariantPair<Pair_NullableString_NullableIntElement> direct = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_interval = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_reverse = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_w_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_w_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_w_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_h_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_h_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_h_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_x = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_x_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_x_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_x_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_y_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_y_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_y_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_y = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_s = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_a_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_s_start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_a_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_s_max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_a_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> resize_s_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> force_fire = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slow_per = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slow_time = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slide = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slide_speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slide_delay = new();
	public VariantPair<Pair_NullableString_NullableIntElement> slide_stamp = new();
	public VariantPair<Pair_NullableString_NullableIntElement> wait_time = new();
	public VariantPair<Pair_NullableString_NullableIntElement> wait_time2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> shake = new();
	public VariantPair<Pair_NullableString_NullableIntElement> flash = new();
	public VariantPair<Pair_NullableString_NullableIntElement> flash_anime = new();
	public VariantPair<Pair_NullableString_NullableIntElement> flash_image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> collision = new();
	public VariantPair<Pair_NullableString_NullableIntElement> afterdeath = new();
	public VariantPair<Pair_NullableString_NullableIntElement> afterhit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> str_ratio = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attr = new();
	public VariantPair<Pair_NullableString_NullableIntElement> add = new();
	public VariantPair<Pair_NullableString_NullableIntElement> add_all = new();
	public VariantPair<Pair_NullableString_NullableIntElement> add_per = new();
	public VariantPair<Pair_NullableString_NullableIntElement> damage = new();
	public VariantPair<Pair_NullableString_NullableIntElement> damage_range_adjust = new();
	public VariantPair<Pair_NullableString_NullableIntElement> attack_us = new();
	public VariantPair<Pair_NullableString_NullableIntElement> allfunc = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bom = new();
	public VariantPair<Pair_NullableString_NullableIntElement> homing = new();
	public VariantPair<Pair_NullableString_NullableIntElement> homing2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> forward = new();
	public VariantPair<Pair_NullableString_NullableIntElement> far = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hard = new();
	public VariantPair<Pair_NullableString_NullableIntElement> hard2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> onehit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> offset_attr = new();
	public VariantPair<Pair_NullableString_NullableIntElement> knock = new();
	public VariantPair<Pair_NullableString_NullableIntElement> knock_speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> knock_power = new();
	public VariantPair<Pair_NullableString_NullableIntElement> range = new();
	public VariantPair<Pair_NullableString_NullableIntElement> range_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> check = new();
	public VariantPair<Pair_NullableString_NullableIntElement> speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> origin = new();
	public VariantPair<Pair_NullableString_NullableIntElement> random_space = new();
	public VariantPair<Pair_NullableString_NullableIntElement> random_space_min = new();
	public VariantPair<Pair_NullableString_NullableIntElement> time = new();
	public VariantPair<Pair_NullableString_NullableIntElement> height = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rush = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rush_interval = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rush_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> rush_random_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> follow = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start_degree_fix = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start_degree_turnunit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start_degree_type = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start_random_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> drop_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> drop_degree2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> joint_skill = new();
	public VariantPair<Pair_NullableString_NullableIntElement> send_target = new();
	public VariantPair<Pair_NullableString_NullableIntElement> send_image_degree = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next4 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next_order = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next_last = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next_first = new();
	public VariantPair<Pair_NullableString_NullableIntElement> next_interval = new();
	public VariantPair<Pair_NullableString_NullableIntElement> pair_next = new();
	public VariantPair<Pair_NullableString_NullableIntElement> item_type = new();
	public VariantPair<Pair_NullableString_NullableIntElement> item_sort = new();
	public VariantPair<Pair_NullableString_NullableIntElement> item_nosell = new();
	public VariantPair<Pair_NullableString_NullableIntElement> price = new();
	public VariantPair<Pair_NullableString_NullableIntElement> summon_level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> fkey = new();
	public VariantPair<Pair_NullableString_NullableIntElement> gun_delay = new();
	public VariantPair<Pair_NullableString_NullableIntElement> ground = new();
	public VariantPair<Pair_NullableString_NullableIntElement> str = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> icon = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> cutin = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> yorozu = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> wave = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> sound = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> add2 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> next2 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> next3 = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> just_next = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> color = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> ray = new();
	public VariantPair<StringArrayElement> offset = new();
	public VariantPair<StringArrayElement> friend = new();

	public void Dispose()
	{
		force_ray.Dispose();
		bright.Dispose();
		func.Dispose();
		name.Dispose();
		sortkey.Dispose();
		special.Dispose();
		delay.Dispose();
		quickreload.Dispose();
		help.Dispose();
		hide_help.Dispose();
		msg.Dispose();
		picture.Dispose();
		value.Dispose();
		talent.Dispose();
		exp_per.Dispose();
		movetype.Dispose();
		type.Dispose();
		w.Dispose();
		h.Dispose();
		a.Dispose();
		mp.Dispose();
		image.Dispose();
		alpha_tip.Dispose();
		alpha_butt.Dispose();
		anime.Dispose();
		anime_interval.Dispose();
		center.Dispose();
		d360.Dispose();
		d360_adj.Dispose();
		rotate.Dispose();
		direct.Dispose();
		resize_interval.Dispose();
		resize_start.Dispose();
		resize_reverse.Dispose();
		resize_w.Dispose();
		resize_w_start.Dispose();
		resize_w_max.Dispose();
		resize_w_min.Dispose();
		resize_h_min.Dispose();
		resize_h_max.Dispose();
		resize_h_start.Dispose();
		resize_h.Dispose();
		resize_x.Dispose();
		resize_x_start.Dispose();
		resize_x_max.Dispose();
		resize_x_min.Dispose();
		resize_y_min.Dispose();
		resize_y_max.Dispose();
		resize_y_start.Dispose();
		resize_y.Dispose();
		resize_a.Dispose();
		resize_s.Dispose();
		resize_a_start.Dispose();
		resize_s_start.Dispose();
		resize_a_max.Dispose();
		resize_s_max.Dispose();
		resize_a_min.Dispose();
		resize_s_min.Dispose();
		force_fire.Dispose();
		slow_per.Dispose();
		slow_time.Dispose();
		slide.Dispose();
		slide_speed.Dispose();
		slide_delay.Dispose();
		slide_stamp.Dispose();
		wait_time.Dispose();
		wait_time2.Dispose();
		shake.Dispose();
		flash.Dispose();
		flash_anime.Dispose();
		flash_image.Dispose();
		collision.Dispose();
		afterdeath.Dispose();
		afterhit.Dispose();
		str_ratio.Dispose();
		attr.Dispose();
		add.Dispose();
		add_all.Dispose();
		add_per.Dispose();
		damage.Dispose();
		damage_range_adjust.Dispose();
		attack_us.Dispose();
		allfunc.Dispose();
		bom.Dispose();
		homing.Dispose();
		homing2.Dispose();
		forward.Dispose();
		far.Dispose();
		hard.Dispose();
		hard2.Dispose();
		onehit.Dispose();
		offset_attr.Dispose();
		knock.Dispose();
		knock_speed.Dispose();
		knock_power.Dispose();
		range.Dispose();
		range_min.Dispose();
		check.Dispose();
		speed.Dispose();
		origin.Dispose();
		random_space.Dispose();
		random_space_min.Dispose();
		time.Dispose();
		height.Dispose();
		rush.Dispose();
		rush_interval.Dispose();
		rush_degree.Dispose();
		rush_random_degree.Dispose();
		follow.Dispose();
		start_degree.Dispose();
		start_degree_fix.Dispose();
		start_degree_turnunit.Dispose();
		start_degree_type.Dispose();
		start_random_degree.Dispose();
		drop_degree.Dispose();
		drop_degree2.Dispose();
		joint_skill.Dispose();
		send_target.Dispose();
		send_image_degree.Dispose();
		next.Dispose();
		next4.Dispose();
		next_order.Dispose();
		next_last.Dispose();
		next_first.Dispose();
		next_interval.Dispose();
		pair_next.Dispose();
		item_type.Dispose();
		item_sort.Dispose();
		item_nosell.Dispose();
		price.Dispose();
		summon_level.Dispose();
		fkey.Dispose();
		gun_delay.Dispose();
		ground.Dispose();
		str.Dispose();
		icon.Dispose();
		cutin.Dispose();
		yorozu.Dispose();
		wave.Dispose();
		sound.Dispose();
		add2.Dispose();
		next2.Dispose();
		next3.Dispose();
		just_next.Dispose();
		color.Dispose();
		ray.Dispose();
		offset.Dispose();
		friend.Dispose();
	}
}
public partial struct PowerNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }
	public DisposableList<VariantPair<Pair_NullableString_NullableIntElement>> Others = new();

	public VariantPair<Pair_NullableString_NullableIntElement> castle_battle = new();
	public VariantPair<Pair_NullableString_NullableIntElement> @event = new();
	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> help = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master = new();
	public VariantPair<Pair_NullableString_NullableIntElement> flag = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bgm = new();
	public VariantPair<Pair_NullableString_NullableIntElement> volume = new();
	public VariantPair<Pair_NullableString_NullableIntElement> diplomacy = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable_select = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable_talent = new();
	public VariantPair<Pair_NullableString_NullableIntElement> free_raise = new();
	public VariantPair<Pair_NullableString_NullableIntElement> money = new();
	public VariantPair<Pair_NullableString_NullableIntElement> fix = new();
	public VariantPair<Pair_NullableString_NullableIntElement> training_average = new();
	public VariantPair<Pair_NullableString_NullableIntElement> base_merits = new();
	public VariantPair<Pair_NullableString_NullableIntElement> base_loyal = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head3 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head4 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head5 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> head6 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> diff = new();
	public VariantPair<Pair_NullableString_NullableIntElement> yabo = new();
	public VariantPair<Pair_NullableString_NullableIntElement> kosen = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master3 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master4 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master5 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> master6 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> enable = new();
	public VariantPair<Pair_NullableString_NullableIntElement> training_up = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> home = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> diplo = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> league = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> enemy_power = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> merits = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> loyals = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> merce = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();
	public VariantPair<StringArrayElement> staff = new();
	public VariantPair<StringArrayElement> friend = new();
	public VariantPair<StringElement> text = new();

	public void Dispose()
	{
		castle_battle.Dispose();
		@event.Dispose();
		name.Dispose();
		help.Dispose();
		master.Dispose();
		flag.Dispose();
		bgm.Dispose();
		volume.Dispose();
		diplomacy.Dispose();
		enable_select.Dispose();
		enable_talent.Dispose();
		free_raise.Dispose();
		money.Dispose();
		fix.Dispose();
		training_average.Dispose();
		base_merits.Dispose();
		base_loyal.Dispose();
		head.Dispose();
		head2.Dispose();
		head3.Dispose();
		head4.Dispose();
		head5.Dispose();
		head6.Dispose();
		diff.Dispose();
		yabo.Dispose();
		kosen.Dispose();
		master2.Dispose();
		master3.Dispose();
		master4.Dispose();
		master5.Dispose();
		master6.Dispose();
		enable.Dispose();
		training_up.Dispose();
		Others.Dispose();
		home.Dispose();
		diplo.Dispose();
		league.Dispose();
		enemy_power.Dispose();
		merits.Dispose();
		loyals.Dispose();
		merce.Dispose();
		member.Dispose();
		Others.Dispose();
		staff.Dispose();
		friend.Dispose();
		Others.Dispose();
		text.Dispose();
		Others.Dispose();
	}
}
public partial struct ObjectNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> skill = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> color = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();
	public VariantPair<Pair_NullableString_NullableIntElement> front = new();
	public VariantPair<Pair_NullableString_NullableIntElement> width = new();
	public VariantPair<Pair_NullableString_NullableIntElement> height = new();
	public VariantPair<Pair_NullableString_NullableIntElement> alpha = new();
	public VariantPair<Pair_NullableString_NullableIntElement> type = new();
	public VariantPair<Pair_NullableString_NullableIntElement> breakfire = new();
	public VariantPair<Pair_NullableString_NullableIntElement> land_base = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_stop = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_wall2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> no_arc_hit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> radius = new();
	public VariantPair<Pair_NullableString_NullableIntElement> blk = new();
	public VariantPair<Pair_NullableString_NullableIntElement> w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image2 = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image2_w = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image2_h = new();
	public VariantPair<Pair_NullableString_NullableIntElement> image2_a = new();
	public VariantPair<Pair_NullableString_NullableIntElement> ground = new();

	public void Dispose()
	{
		skill.Dispose();
		color.Dispose();
		member.Dispose();
		front.Dispose();
		width.Dispose();
		height.Dispose();
		alpha.Dispose();
		type.Dispose();
		breakfire.Dispose();
		land_base.Dispose();
		no_stop.Dispose();
		no_wall2.Dispose();
		no_arc_hit.Dispose();
		radius.Dispose();
		blk.Dispose();
		w.Dispose();
		h.Dispose();
		a.Dispose();
		image.Dispose();
		image2.Dispose();
		image2_w.Dispose();
		image2_h.Dispose();
		image2_a.Dispose();
		ground.Dispose();
	}
}
public partial struct DungeonNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> max = new();
	public VariantPair<Pair_NullableString_NullableIntElement> move_speed = new();
	public VariantPair<Pair_NullableString_NullableIntElement> prefix = new();
	public VariantPair<Pair_NullableString_NullableIntElement> suffix = new();
	public VariantPair<Pair_NullableString_NullableIntElement> lv_adjust = new();
	public VariantPair<Pair_NullableString_NullableIntElement> open = new();
	public VariantPair<Pair_NullableString_NullableIntElement> limit = new();
	public VariantPair<Pair_NullableString_NullableIntElement> bgm = new();
	public VariantPair<Pair_NullableString_NullableIntElement> volume = new();
	public VariantPair<Pair_NullableString_NullableIntElement> blind = new();
	public VariantPair<Pair_NullableString_NullableIntElement> base_level = new();
	public VariantPair<Pair_NullableString_NullableIntElement> map = new();
	public VariantPair<Pair_NullableString_NullableIntElement> floor = new();
	public VariantPair<Pair_NullableString_NullableIntElement> wall = new();
	public VariantPair<Pair_NullableString_NullableIntElement> start = new();
	public VariantPair<Pair_NullableString_NullableIntElement> goal = new();
	public VariantPair<Pair_NullableString_NullableIntElement> monster_num = new();
	public VariantPair<Pair_NullableString_NullableIntElement> box = new();
	public VariantPair<Pair_NullableString_NullableIntElement> item_num = new();
	public VariantPair<Pair_NullableString_NullableIntElement> item_text = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> color = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> home = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> ray = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> monster = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> item = new();

	public void Dispose()
	{
		name.Dispose();
		max.Dispose();
		move_speed.Dispose();
		prefix.Dispose();
		suffix.Dispose();
		lv_adjust.Dispose();
		open.Dispose();
		limit.Dispose();
		bgm.Dispose();
		volume.Dispose();
		blind.Dispose();
		base_level.Dispose();
		map.Dispose();
		floor.Dispose();
		wall.Dispose();
		start.Dispose();
		goal.Dispose();
		monster_num.Dispose();
		box.Dispose();
		item_num.Dispose();
		item_text.Dispose();
		color.Dispose();
		home.Dispose();
		ray.Dispose();
		monster.Dispose();
		item.Dispose();
	}
}
public partial struct MovetypeNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> help = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> consti = new();

	public void Dispose()
	{
		name.Dispose();
		help.Dispose();
		consti.Dispose();
	}
}
public partial struct SkillsetNode : IInheritableNode
{
    public uint Kind { get; set; }
    public uint BracketLeft { get; set; }
    public uint BracketRight { get; set; }
    public uint? Super { get; set; }
    public uint Name { get; set; }

	public VariantPair<Pair_NullableString_NullableIntElement> name = new();
	public VariantPair<Pair_NullableString_NullableIntElement> back = new();
	public VariantPair<Pair_NullableString_NullableInt_ArrayElement> member = new();

	public void Dispose()
	{
		name.Dispose();
		back.Dispose();
		member.Dispose();
	}
}
