#nullable enable
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
namespace Wahren.AbstractSyntaxTree.Parser;

public static partial class Parser
{
	public static bool Parse(ref Context context, ref Result result)
    {
        ref var source = ref result.Source;
        if (source.Count != 0 && source[0].Count != 0 && source[0][0] == '\ufeff')
        {
            source[0].RemoveAt(0);
        }

        ref var tokenList = ref result.TokenList;
        while (ReadUsefulToken(ref context, ref result))
        {
            var hash = StringHashUtility.Calc(result.GetSpan(tokenList.LastIndex));
            switch (hash)
            {
                case 0x0000000000151593UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.race;
                    if (!ParseRace(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000000162D72UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.spot;
                    if (!ParseSpot(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000000000017AD9CUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.unit;
                    if (!ParseUnit(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000000000167A00FUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.@class;
                    if (!ParseClass(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000001A8A13FUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.@event;
                    if (!ParseEvent(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000001BB2D9DUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.field;
                    if (!ParseField(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000001BB37CBUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.fight;
                    if (!ParseEvent(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000002DE2982UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.power;
                    if (!ParsePower(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000003309300UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.skill;
                    if (!ParseSkill(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000000000333EAE2UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.sound;
                    if (!ParseSound(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000000000337A8C6UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.story;
                    if (!ParseStory(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x00000000038973F3UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.voice;
                    if (!ParseVoice(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000003A63E51UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.world;
                    if (!ParseEvent(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000037625C31UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.detail;
                    if (!ParseDetail(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x00000000647C1271UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.@object;
                    if (!ParseObject(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x00000007910184D4UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.context;
                    if (!ParseContext(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000000842B1F90FUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.dungeon;
                    if (!ParseDungeon(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000001F51C769275UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.movetype;
                    if (!ParseMovetype(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x000002724A47B9DCUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.scenario;
                    if (!ParseScenario(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x00000277220E7EDFUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.skillset;
                    if (!ParseSkillset(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x00002284E289189DUL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.attribute;
                    if (!ParseAttribute(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                case 0x0000685CF2FB2764UL:
                    tokenList.GetKind(tokenList.LastIndex) = TokenKind.workspace;
                    if (!ParseWorkspace(ref context, ref result))
                    {
                        return false;
                    }
                    break;
                default:
                    result.ErrorAdd_StructureKindOrCommentIsExpected();
                    return false;
            }
        }

        return true;
    }
}
