#nullable enable
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>

namespace Wahren.AbstractSyntaxTree.Modifier;

public static partial class PerFileModifier
{
}
