global using System.Collections.Generic;
namespace Wahren.AbstractSyntaxTree.TextTemplateHelper;

public struct ActionInfo
{
    public string Name;
    public int Min;
    public int Max;
    public ReferenceKind[] ReferenceKinds;

    public ActionInfo(string name, int min, int max)
    {
        Name = name;
        Min = min;
        Max = max;
        ReferenceKinds = System.Array.Empty<ReferenceKind>();
    }

    public ActionInfo(string name, int min, int max, params ReferenceKind[] referenceKinds)
    {
        Name = name;
        Min = min;
        Max = max;
        ReferenceKinds = referenceKinds;
    }

    public void Deconstruct(out string name, out int min, out int max)
    {
        name = Name;
        min = Min;
        max = Max;
    }

    public static readonly string[] Specials = new string[]
    {
        "if",
        "rif",
        "while",
        "next",
        "return",
        "break",
        "continue",
    };

    public static readonly ActionInfo[] Normals = new ActionInfo[]
    {
        new("bg", 1, 2),
        new("vc", 0, int.MaxValue),
        new("add", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("div", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("mod", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("msg", 0, int.MaxValue),
        new("mul", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("per", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("set", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("sub", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("win", 0, int.MaxValue),
        new("addv", 2, 2, ReferenceKind.StringVariableWriter, ReferenceKind.Text | ReferenceKind.StringVariableReader),
        new("call", 1, 1, ReferenceKind.Event),
        new("chat", 0, int.MaxValue),
        new("exit", 0, 1),
        new("face", 3, 5),
        new("font", 0, 3),
        new("msg2", 0, int.MaxValue),
        new("play", 0, int.MaxValue),
        new("ppl1", 0, int.MaxValue),
        new("save", 0, 0),
        new("setv", 2, 2, ReferenceKind.StringVariableWriter, ReferenceKind.Text | ReferenceKind.StringVariableReader),
        new("stop", 0, int.MaxValue),
        new("subv", 2, 2, ReferenceKind.StringVariableWriter, ReferenceKind.Text | ReferenceKind.StringVariableReader),
        new("talk", 0, int.MaxValue),
        new("wait", 0, 1),
        new("zoom", 1, 1),
        new("chat2", 0, int.MaxValue),
        new("citom", 0, int.MaxValue),
        new("clear", 1, 1, ReferenceKind.StringVariableWriter),
        new("erase", 0, int.MaxValue),
        new("event", 1, 3),
        new("face2", 0, int.MaxValue),
        new("focus", 0, 1),
        new("fontc", 0, 3),
        new("gread", 2, 3, ReferenceKind.GlobalVariableReader | ReferenceKind.StringVariableReader, ReferenceKind.NumberVariableWriter, ReferenceKind.StringVariableWriter),
        new("image", 1, 5),
        new("index", 3, 3, ReferenceKind.StringVariableReader, ReferenceKind.Number | ReferenceKind.NumberVariableReader, ReferenceKind.StringVariableWriter),
        new("pushv", 2, 3),
        new("setPM", 2, 2),
        new("setud", 2, 2, ReferenceKind.GlobalStringVariableReader, ReferenceKind.StringVariableWriter),
        new("shake", 0, 1),
        new("talk2", 0, int.MaxValue),
        new("title", 2, 2, ReferenceKind.Text, ReferenceKind.Number | ReferenceKind.NumberVariableReader),
        new("addstr", 2, 2, ReferenceKind.StringVariableWriter, ReferenceKind.Text),
        new("addVar", 2, 2, ReferenceKind.StringVariableWriter, ReferenceKind.Text | ReferenceKind.StringVariableReader),
        new("choice", 2, int.MaxValue),
        new("dialog", 1, 1, ReferenceKind.Text),
        new("fadein", 0, 1),
        new("gwrite", 2, 3, ReferenceKind.GlobalVariableWriter | ReferenceKind.StringVariableWriter, ReferenceKind.NumberVariableReader, ReferenceKind.StringVariableReader),
        new("locate", 1, 2),
        new("playSE", 1, 1),
        new("scroll", 1, 2),
        new("select", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.Text),
        new("setbcg", 0, int.MaxValue),
        new("setVar", 0, int.MaxValue),
        new("shadow", 0, 6),
        new("subVar", 0, int.MaxValue),
        new("title2", 2, 2, ReferenceKind.Text, ReferenceKind.Number | ReferenceKind.NumberVariableReader),
        new("volume", 1, 1, ReferenceKind.Number | ReferenceKind.NumberVariableReader),
        new("addCapa", 0, int.MaxValue),
        new("addGain", 0, int.MaxValue),
        new("addItem", 0, int.MaxValue),
        new("addSpot", 0, int.MaxValue),
        new("addUnit", 0, int.MaxValue),
        new("dialogF", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.Text),
        new("doskill", 5, 5),
        new("fadeout", 0, 1),
        new("levelup", 0, int.MaxValue),
        new("loopBGM", 1, int.MaxValue),
        new("minimap", 0, int.MaxValue),
        new("picture", 3, 5),
        new("playBGM", 0, 1),
        new("pushCon", 3, 3, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableReader | ReferenceKind.Unit | ReferenceKind.Class, ReferenceKind.NumberVariableWriter),
        new("pushSex", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushVar", 2, 2, ReferenceKind.StringVariableReader, ReferenceKind.NumberVariableWriter),
        new("routine", 1, 1),
        new("scroll2", 1, 1, ReferenceKind.Unit | ReferenceKind.Spot),
        new("setCapa", 2, 2),
        new("setDone", 0, int.MaxValue),
        new("setGain", 2, 2),
        new("shuffle", 1, 1),
        new("stopBGM", 0, 0),
        new("storePM", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("storeud", 2, 2, ReferenceKind.GlobalStringVariableWriter, ReferenceKind.StringVariableReader),
        new("addDiplo", 0, int.MaxValue),
        new("addLevel", 0, int.MaxValue),
        new("addLimit", 0, int.MaxValue),
        new("addLoyal", 0, int.MaxValue),
        new("addMoney", 0, int.MaxValue),
        new("addPower", 0, int.MaxValue),
        new("addSkill", 0, int.MaxValue),
        new("addTroop", 0, int.MaxValue),
        new("addTrust", 0, int.MaxValue),
        new("aimTroop", 0, int.MaxValue),
        new("clearVar", 0, int.MaxValue),
        new("darkness", 0, 4),
        new("exitItem", 0, int.MaxValue),
        new("hideLink", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableReader | ReferenceKind.Spot),
        new("hideSpot", 1, 1, ReferenceKind.StringVariableReader | ReferenceKind.Spot),
        new("linkSpot", 2, 4),
        new("openGoal", 0, int.MaxValue),
        new("picture2", 0, int.MaxValue),
        new("pushCapa", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.NumberVariableWriter),
        new("pushGain", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power | ReferenceKind.Spot, ReferenceKind.NumberVariableWriter),
        new("pushItem", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Skill, ReferenceKind.NumberVariableWriter),
        new("pushRand", 1, 1, ReferenceKind.NumberVariableWriter),
        new("pushRank", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.NumberVariableWriter),
        new("pushTurn", 1, 1, ReferenceKind.NumberVariableWriter),
        new("roamUnit", 0, int.MaxValue),
        new("setDiplo", 0, int.MaxValue),
        new("setLevel", 0, int.MaxValue),
        new("setLimit", 0, int.MaxValue),
        new("setMoney", 0, int.MaxValue),
        new("setTruce", 0, int.MaxValue),
        new("showCamp", 0, int.MaxValue),
        new("showFace", 0, int.MaxValue),
        new("showPict", 0, int.MaxValue),
        new("showSpot", 0, int.MaxValue),
        new("spotmark", 0, 2),
        new("showParty", 1, 1, ReferenceKind.Boolean),
        new("addCastle", 0, int.MaxValue),
        new("addFriend", 0, int.MaxValue),
        new("addMerits", 0, int.MaxValue),
        new("addSkill2", 0, int.MaxValue),
        new("addStatus", 0, int.MaxValue),
        new("changeMap", 0, int.MaxValue),
        new("clickWait", 0, int.MaxValue),
        new("closeGoal", 0, int.MaxValue),
        new("ctrlTroop", 0, int.MaxValue),
        new("entryItem", 0, int.MaxValue),
        new("equipItem", 0, int.MaxValue),
        new("eraseItem", 0, int.MaxValue),
        new("eraseUnit", 0, int.MaxValue),
        new("formTroop", 0, int.MaxValue),
        new("freeTroop", 0, int.MaxValue),
        new("haltTroop", 0, int.MaxValue),
        new("hideBlind", 0, 0),
        new("hideChara", 1, 1),
        new("hideImage", 0, int.MaxValue),
        new("moveTroop", 0, int.MaxValue),
        new("playWorld", 0, 0),
        new("pushDeath", 0, int.MaxValue),
        new("pushDiplo", 3, 3, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.NumberVariableWriter),
        new("pushForce", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushLevel", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushLimit", 1, 1, ReferenceKind.NumberVariableWriter),
        new("pushLoyal", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushMoney", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushRand2", 1, 1, ReferenceKind.NumberVariableWriter),
        new("pushTrain", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.NumberVariableWriter),
        new("pushTrust", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("resetTime", 0, int.MaxValue),
        new("resetZone", 0, 0),
        new("roamUnit2", 0, int.MaxValue),
        new("setArbeit", 0, int.MaxValue),
        new("setCastle", 0, int.MaxValue),
        new("setLeague", 2, 3),
        new("setStatus", 0, int.MaxValue),
        new("showBlind", 0, 0),
        new("showChara", 3, 5),
        new("showImage", 0, int.MaxValue),
        new("stopTroop", 0, int.MaxValue),
        new("terminate", 0, 0),
        new("worldskin", 0, int.MaxValue),
        new("backScroll", 0, 0),
        new("changeRace", 0, int.MaxValue),
        new("endingRoll", 0, int.MaxValue),
        new("erasePower", 0, int.MaxValue),
        new("eraseSkill", 0, int.MaxValue),
        new("eraseTroop", 0, int.MaxValue),
        new("eraseUnit2", 0, int.MaxValue),
        new("hideEscape", 0, int.MaxValue),
        new("linkEscape", 2, 4),
        new("playBattle", 0, 0),
        new("pushCastle", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.NumberVariableWriter),
        new("pushMerits", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.NumberVariableWriter),
        new("pushStatus", 3, 3, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.Status, ReferenceKind.NumberVariableWriter),
        new("reloadMenu", 1, 1, ReferenceKind.Boolean),
        new("removeSpot", 0, int.MaxValue),
        new("resetTruce", 0, int.MaxValue),
        new("setDungeon", 0, int.MaxValue),
        new("shiftTroop", 0, int.MaxValue),
        new("shuffleVar", 0, int.MaxValue),
        new("skillTroop", 0, int.MaxValue),
        new("sleepTroop", 0, int.MaxValue),
        new("smoveTroop", 0, int.MaxValue),
        new("speedTroop", 0, int.MaxValue),
        new("storeDeath", 0, int.MaxValue),
        new("storeIndex", 0, int.MaxValue),
        new("unionPower", 0, int.MaxValue),
        new("activeTroop", 0, int.MaxValue),
        new("addTraining", 0, int.MaxValue),
        new("battleEvent", 1, 1, ReferenceKind.Event),
        new("changeClass", 0, int.MaxValue),
        new("choiceTitle", 0, 1),
        new("eraseFriend", 0, int.MaxValue),
        new("hidePicture", 0, int.MaxValue),
        new("pushSpotPos", 3, 3, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableWriter),
        new("pushTrainUp", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.NumberVariableWriter),
        new("removeSkill", 0, int.MaxValue),
        new("removeTroop", 0, int.MaxValue),
        new("resetLeague", 1, 2),
        new("scrollSpeed", 1, 1, ReferenceKind.NumberVariableReader | ReferenceKind.Number),
        new("setTraining", 0, int.MaxValue),
        new("shiftTroop2", 0, int.MaxValue),
        new("showDungeon", 1, 1, ReferenceKind.StringVariableReader | ReferenceKind.Dungeon),
        new("showPicture", 0, int.MaxValue),
        new("unctrlTroop", 0, int.MaxValue),
        new("addBaseLevel", 0, int.MaxValue),
        new("changeCastle", 0, int.MaxValue),
        new("changeMaster", 0, int.MaxValue),
        new("changePlayer", 0, int.MaxValue),
        new("darkness_off", 0, int.MaxValue),
        new("doGameEnding", 0, int.MaxValue),
        new("hideSpotMark", 0, 0),
        new("moveTroopFix", 0, int.MaxValue),
        new("retreatTroop", 0, int.MaxValue),
        new("reverseChara", 1, 1),
        new("setBaseLevel", 0, int.MaxValue),
        new("setGameClear", 0, 1),
        new("setPowerHome", 0, int.MaxValue),
        new("showPolitics", 1, 1, ReferenceKind.Boolean),
        new("showSpotMark", 1, 2),
        new("storeAllSpot", 1, 1, ReferenceKind.StringVariableWriter),
        new("addPowerMerce", 0, int.MaxValue),
        new("addPowerStaff", 0, int.MaxValue),
        new("addTrainingUp", 0, int.MaxValue),
        new("changeDungeon", 0, int.MaxValue),
        new("pushBaseLevel", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.NumberVariableWriter),
        new("setEnemyPower", 0, int.MaxValue),
        new("setTrainingUp", 0, int.MaxValue),
        new("setWorldMusic", 0, 0),
        new("smoveTroopFix", 0, int.MaxValue),
        new("storeAllPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeComPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeIndexVar", 0, int.MaxValue),
        new("storeNextSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableWriter),
        new("storeNowPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeRectUnit", 5, 5, ReferenceKind.RedBlue, ReferenceKind.NumberVariableReader | ReferenceKind.Number, ReferenceKind.NumberVariableReader | ReferenceKind.Number, ReferenceKind.NumberVariableReader | ReferenceKind.Number, ReferenceKind.NumberVariableReader | ReferenceKind.Number, ReferenceKind.NumberVariableWriter),
        new("storeSkillset", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Skillset, ReferenceKind.StringVariableWriter),
        new("storeTodoUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.ClassTypeReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("addPowerMerce2", 0, int.MaxValue),
        new("addPowerStaff2", 0, int.MaxValue),
        new("changePowerFix", 0, int.MaxValue),
        new("eraseUnitTroop", 0, int.MaxValue),
        new("pushBattleHome", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableWriter),
        new("pushBattleRect", 2, 2, ReferenceKind.NumberVariableWriter, ReferenceKind.NumberVariableWriter),
        new("pushCountPower", 1, 1, ReferenceKind.NumberVariableWriter),
        new("storeAliveUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.ClassTypeReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeAllTalent", 1, 1, ReferenceKind.StringVariableWriter),
        new("changePowerFlag", 0, int.MaxValue),
        new("changePowerName", 0, int.MaxValue),
        new("changeSpotImage", 0, int.MaxValue),
        new("erasePowerMerce", 0, int.MaxValue),
        new("erasePowerStaff", 0, int.MaxValue),
        new("resetEnemyPower", 0, int.MaxValue),
        new("resetWorldMusic", 0, 0),
        new("setDungeonFloor", 0, int.MaxValue),
        new("storeBattleSpot", 1, 1, ReferenceKind.StringVariableWriter),
        new("storePlayerUnit", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeRaceOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeSpotOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeUnitOfSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableWriter),
        new("storeAttackPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeClassOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeNeutralSpot", 1, 1, ReferenceKind.StringVariableWriter),
        new("storePlayerPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storePowerOfSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableWriter),
        new("storePowerOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeSkillOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeSpotOfPower", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.StringVariableWriter),
        new("storeTalentPower", 2, 2, ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeUnitOfPower", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("clearBattleRecord", 0, 0),
        new("storeDefensePower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeLeaderOfSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableWriter),
        new("storeMasterOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storeMemberOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
        new("storePowerOfForce", 2, 2, ReferenceKind.NumberVariableReader | ReferenceKind.Number, ReferenceKind.StringVariableWriter),
        new("storeSpotOfBattle", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeLeaderOfPower", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.StringVariableWriter),
        new("storeMasterOfPower", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Power, ReferenceKind.StringVariableWriter),
        new("storePowerOfAttack", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeNonPlayerPower", 1, 1, ReferenceKind.StringVariableWriter),
        new("storePowerOfDefense", 1, 1, ReferenceKind.StringVariableWriter),
        new("storeRoamUnitOfSpot", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Spot, ReferenceKind.StringVariableWriter),
        new("storeBaseClassOfUnit", 2, 2, ReferenceKind.StringVariableReader | ReferenceKind.Unit, ReferenceKind.StringVariableWriter),
    };
}
