global using System.Collections.Generic;
namespace Wahren.AbstractSyntaxTree.TextTemplateHelper;

public struct ActionInfo
{
    public string Name;
    public int Min;
    public int Max;
    public int? EnglishCount;
    public Dictionary<int, ArgumentInfo[]> Dictionary;

    public ActionInfo(string name, int min, int max, int? englishCount = null, Dictionary<int, ArgumentInfo[]>? dictionary = null)
    {
        Name = name;
        Min = min;
        Max = max;
        EnglishCount = englishCount;
        Dictionary = dictionary ?? new();
    }

    public void Deconstruct(out string name, out int min, out int max)
    {
        name = Name;
        min = Min;
        max = Max;
    }

    public void Deconstruct(out string name, out int min, out int max, out int? englishCount)
    {
        name = Name;
        min = Min;
        max = Max;
        englishCount = EnglishCount;
    }

    public void Deconstruct(out string name, out int min, out int max, out int? englishCount, out Dictionary<int, ArgumentInfo[]> dictionary)
    {
        name = Name;
        min = Min;
        max = Max;
        englishCount = EnglishCount;
        dictionary = Dictionary;
    }

    public static readonly string[] Specials = new string[]
    {
        "if",
        "rif",
        "while",
        "next",
        "return",
        "break",
        "continue",
    };

    public static readonly ActionInfo[] Normals = new ActionInfo[]
    {
        new("bg", 0, int.MaxValue),
        new("vc", 0, int.MaxValue),
        new("add", 0, int.MaxValue),
        new("div", 0, int.MaxValue),
        new("mod", 0, int.MaxValue),
        new("msg", 0, int.MaxValue),
        new("mul", 0, int.MaxValue),
        new("per", 0, int.MaxValue),
        new("set", 0, int.MaxValue),
        new("sub", 0, int.MaxValue),
        new("win", 0, int.MaxValue),
        new("addv", 0, int.MaxValue),
        new("call", 0, int.MaxValue),
        new("chat", 0, int.MaxValue),
        new("exit", 0, int.MaxValue),
        new("face", 0, int.MaxValue),
        new("font", 0, int.MaxValue),
        new("msg2", 0, int.MaxValue),
        new("play", 0, int.MaxValue),
        new("ppl1", 0, int.MaxValue),
        new("save", 0, int.MaxValue),
        new("setv", 0, int.MaxValue),
        new("stop", 0, int.MaxValue),
        new("subv", 0, int.MaxValue),
        new("talk", 0, int.MaxValue),
        new("wait", 0, int.MaxValue),
        new("zoom", 0, int.MaxValue),
        new("chat2", 0, int.MaxValue),
        new("citom", 0, int.MaxValue),
        new("clear", 0, int.MaxValue),
        new("erase", 0, int.MaxValue),
        new("event", 0, int.MaxValue),
        new("face2", 0, int.MaxValue),
        new("focus", 0, int.MaxValue),
        new("fontc", 0, int.MaxValue),
        new("gread", 0, int.MaxValue),
        new("image", 0, int.MaxValue),
        new("index", 0, int.MaxValue),
        new("pushv", 0, int.MaxValue),
        new("setPM", 0, int.MaxValue),
        new("setud", 0, int.MaxValue),
        new("shake", 0, int.MaxValue),
        new("talk2", 0, int.MaxValue),
        new("title", 0, int.MaxValue),
        new("addstr", 0, int.MaxValue),
        new("addVar", 0, int.MaxValue),
        new("choice", 0, int.MaxValue),
        new("dialog", 0, int.MaxValue),
        new("fadein", 0, int.MaxValue),
        new("gwrite", 0, int.MaxValue),
        new("locate", 0, int.MaxValue),
        new("playSE", 0, int.MaxValue),
        new("scroll", 0, int.MaxValue),
        new("select", 0, int.MaxValue),
        new("setbcg", 0, int.MaxValue),
        new("setVar", 0, int.MaxValue),
        new("shadow", 0, int.MaxValue),
        new("subVar", 0, int.MaxValue),
        new("title2", 0, int.MaxValue),
        new("volume", 0, int.MaxValue),
        new("addCapa", 0, int.MaxValue),
        new("addGain", 0, int.MaxValue),
        new("addItem", 0, int.MaxValue),
        new("addSpot", 0, int.MaxValue),
        new("addUnit", 0, int.MaxValue),
        new("dialogF", 0, int.MaxValue),
        new("doskill", 0, int.MaxValue),
        new("fadeout", 0, int.MaxValue),
        new("levelup", 0, int.MaxValue),
        new("loopBGM", 0, int.MaxValue),
        new("minimap", 0, int.MaxValue),
        new("picture", 0, int.MaxValue),
        new("playBGM", 0, int.MaxValue),
        new("pushCon", 0, int.MaxValue),
        new("pushSex", 0, int.MaxValue),
        new("pushVar", 0, int.MaxValue),
        new("routine", 0, int.MaxValue),
        new("scroll2", 0, int.MaxValue),
        new("setCapa", 0, int.MaxValue),
        new("setDone", 0, int.MaxValue),
        new("setGain", 0, int.MaxValue),
        new("shuffle", 0, int.MaxValue),
        new("stopBGM", 0, int.MaxValue),
        new("storePM", 0, int.MaxValue),
        new("storeud", 0, int.MaxValue),
        new("addDiplo", 0, int.MaxValue),
        new("addLevel", 0, int.MaxValue),
        new("addLimit", 0, int.MaxValue),
        new("addLoyal", 0, int.MaxValue),
        new("addMoney", 0, int.MaxValue),
        new("addPower", 0, int.MaxValue),
        new("addSkill", 0, int.MaxValue),
        new("addTroop", 0, int.MaxValue),
        new("addTrust", 0, int.MaxValue),
        new("aimTroop", 0, int.MaxValue),
        new("clearVar", 0, int.MaxValue),
        new("darkness", 0, int.MaxValue),
        new("exitItem", 0, int.MaxValue),
        new("hideLink", 0, int.MaxValue),
        new("hideSpot", 0, int.MaxValue),
        new("linkSpot", 0, int.MaxValue),
        new("openGoal", 0, int.MaxValue),
        new("picture2", 0, int.MaxValue),
        new("pushCapa", 0, int.MaxValue),
        new("pushGain", 0, int.MaxValue),
        new("pushItem", 0, int.MaxValue),
        new("pushRand", 0, int.MaxValue),
        new("pushRank", 0, int.MaxValue),
        new("pushSpot", 0, int.MaxValue),
        new("pushTurn", 0, int.MaxValue),
        new("roamUnit", 0, int.MaxValue),
        new("setDiplo", 0, int.MaxValue),
        new("setLevel", 0, int.MaxValue),
        new("setLimit", 0, int.MaxValue),
        new("setMoney", 0, int.MaxValue),
        new("setTruce", 0, int.MaxValue),
        new("showCamp", 0, int.MaxValue),
        new("showFace", 0, int.MaxValue),
        new("showPict", 0, int.MaxValue),
        new("showSpot", 0, int.MaxValue),
        new("spotmark", 0, int.MaxValue),
        new("addCastle", 0, int.MaxValue),
        new("addFriend", 0, int.MaxValue),
        new("addMerits", 0, int.MaxValue),
        new("addSkill2", 0, int.MaxValue),
        new("addStatus", 0, int.MaxValue),
        new("changeMap", 0, int.MaxValue),
        new("clickWait", 0, int.MaxValue),
        new("closeGoal", 0, int.MaxValue),
        new("ctrlTroop", 0, int.MaxValue),
        new("entryItem", 0, int.MaxValue),
        new("equipItem", 0, int.MaxValue),
        new("eraseItem", 0, int.MaxValue),
        new("eraseUnit", 0, int.MaxValue),
        new("formTroop", 0, int.MaxValue),
        new("freeTroop", 0, int.MaxValue),
        new("haltTroop", 0, int.MaxValue),
        new("hideBlind", 0, int.MaxValue),
        new("hideChara", 0, int.MaxValue),
        new("hideImage", 0, int.MaxValue),
        new("moveTroop", 0, int.MaxValue),
        new("playWorld", 0, int.MaxValue),
        new("pushDeath", 0, int.MaxValue),
        new("pushDiplo", 0, int.MaxValue),
        new("pushForce", 0, int.MaxValue),
        new("pushLevel", 0, int.MaxValue),
        new("pushLimit", 0, int.MaxValue),
        new("pushLoyal", 0, int.MaxValue),
        new("pushMoney", 0, int.MaxValue),
        new("pushRand2", 0, int.MaxValue),
        new("pushTrain", 0, int.MaxValue),
        new("pushTrust", 0, int.MaxValue),
        new("resetTime", 0, int.MaxValue),
        new("resetZone", 0, int.MaxValue),
        new("roamUnit2", 0, int.MaxValue),
        new("setArbeit", 0, int.MaxValue),
        new("setCastle", 0, int.MaxValue),
        new("setLeague", 0, int.MaxValue),
        new("setStatus", 0, int.MaxValue),
        new("showBlind", 0, int.MaxValue),
        new("showChara", 0, int.MaxValue),
        new("showImage", 0, int.MaxValue),
        new("stopTroop", 0, int.MaxValue),
        new("terminate", 0, int.MaxValue),
        new("worldskin", 0, int.MaxValue),
        new("backScroll", 0, int.MaxValue),
        new("changeRace", 0, int.MaxValue),
        new("endingRoll", 0, int.MaxValue),
        new("erasePower", 0, int.MaxValue),
        new("eraseSkill", 0, int.MaxValue),
        new("eraseTroop", 0, int.MaxValue),
        new("eraseUnit2", 0, int.MaxValue),
        new("hideEscape", 0, int.MaxValue),
        new("linkEscape", 0, int.MaxValue),
        new("playBattle", 0, int.MaxValue),
        new("pushCastle", 0, int.MaxValue),
        new("pushMerits", 0, int.MaxValue),
        new("pushStatus", 0, int.MaxValue),
        new("reloadMenu", 0, int.MaxValue),
        new("removeSpot", 0, int.MaxValue),
        new("resetTruce", 0, int.MaxValue),
        new("setDungeon", 0, int.MaxValue),
        new("shiftTroop", 0, int.MaxValue),
        new("shuffleVar", 0, int.MaxValue),
        new("skillTroop", 0, int.MaxValue),
        new("sleepTroop", 0, int.MaxValue),
        new("smoveTroop", 0, int.MaxValue),
        new("speedTroop", 0, int.MaxValue),
        new("storeDeath", 0, int.MaxValue),
        new("storeIndex", 0, int.MaxValue),
        new("unionPower", 0, int.MaxValue),
        new("activeTroop", 0, int.MaxValue),
        new("addTraining", 0, int.MaxValue),
        new("battleEvent", 0, int.MaxValue),
        new("changeClass", 0, int.MaxValue),
        new("choiceTitle", 0, int.MaxValue),
        new("eraseFriend", 0, int.MaxValue),
        new("hidePicture", 0, int.MaxValue),
        new("pushSpotPos", 0, int.MaxValue),
        new("pushTrainUp", 0, int.MaxValue),
        new("removeSkill", 0, int.MaxValue),
        new("removeTroop", 0, int.MaxValue),
        new("resetLeague", 0, int.MaxValue),
        new("scrollSpeed", 0, int.MaxValue),
        new("setTraining", 0, int.MaxValue),
        new("shiftTroop2", 0, int.MaxValue),
        new("showDungeon", 0, int.MaxValue),
        new("showPicture", 0, int.MaxValue),
        new("unctrlTroop", 0, int.MaxValue),
        new("addBaseLevel", 0, int.MaxValue),
        new("changeCastle", 0, int.MaxValue),
        new("changeMaster", 0, int.MaxValue),
        new("changePlayer", 0, int.MaxValue),
        new("darkness_off", 0, int.MaxValue),
        new("doGameEnding", 0, int.MaxValue),
        new("hideSpotMark", 0, int.MaxValue),
        new("moveTroopFix", 0, int.MaxValue),
        new("retreatTroop", 0, int.MaxValue),
        new("reverseChara", 0, int.MaxValue),
        new("setBaseLevel", 0, int.MaxValue),
        new("setGameClear", 0, int.MaxValue),
        new("setPowerHome", 0, int.MaxValue),
        new("showPolitics", 0, int.MaxValue),
        new("showSpotMark", 0, int.MaxValue),
        new("storeAllSpot", 0, int.MaxValue),
        new("addPowerMerce", 0, int.MaxValue),
        new("addPowerStaff", 0, int.MaxValue),
        new("addTrainingUp", 0, int.MaxValue),
        new("changeDungeon", 0, int.MaxValue),
        new("pushBaseLevel", 0, int.MaxValue),
        new("setEnemyPower", 0, int.MaxValue),
        new("setTrainingUp", 0, int.MaxValue),
        new("setWorldMusic", 0, int.MaxValue),
        new("smoveTroopFix", 0, int.MaxValue),
        new("storeAllPower", 0, int.MaxValue),
        new("storeComPower", 0, int.MaxValue),
        new("storeIndexVar", 0, int.MaxValue),
        new("storeNextSpot", 0, int.MaxValue),
        new("storeNowPower", 0, int.MaxValue),
        new("storeRectUnit", 0, int.MaxValue),
        new("storeSkillset", 0, int.MaxValue),
        new("storeTodoUnit", 0, int.MaxValue),
        new("addPowerMerce2", 0, int.MaxValue),
        new("addPowerStaff2", 0, int.MaxValue),
        new("changePowerFix", 0, int.MaxValue),
        new("eraseUnitTroop", 0, int.MaxValue),
        new("pushBattleHome", 0, int.MaxValue),
        new("pushBattleRect", 0, int.MaxValue),
        new("pushCountPower", 0, int.MaxValue),
        new("storeAliveUnit", 0, int.MaxValue),
        new("storeAllTalent", 0, int.MaxValue),
        new("changePowerFlag", 0, int.MaxValue),
        new("changePowerName", 0, int.MaxValue),
        new("changeSpotImage", 0, int.MaxValue),
        new("erasePowerMerce", 0, int.MaxValue),
        new("erasePowerStaff", 0, int.MaxValue),
        new("resetEnemyPower", 0, int.MaxValue),
        new("resetWorldMusic", 0, int.MaxValue),
        new("setDungeonFloor", 0, int.MaxValue),
        new("storeBattleSpot", 0, int.MaxValue),
        new("storePlayerUnit", 0, int.MaxValue),
        new("storeRaceOfUnit", 0, int.MaxValue),
        new("storeSpotOfUnit", 0, int.MaxValue),
        new("storeUnitOfSpot", 0, int.MaxValue),
        new("storeAttackPower", 0, int.MaxValue),
        new("storeClassOfUnit", 0, int.MaxValue),
        new("storeNeutralSpot", 0, int.MaxValue),
        new("storePlayerPower", 0, int.MaxValue),
        new("storePowerOfSpot", 0, int.MaxValue),
        new("storePowerOfUnit", 0, int.MaxValue),
        new("storeSkillOfUnit", 0, int.MaxValue),
        new("storeSpotOfPower", 0, int.MaxValue),
        new("storeTalentPower", 0, int.MaxValue),
        new("storeUnitOfPower", 0, int.MaxValue),
        new("clearBattleRecord", 0, int.MaxValue),
        new("storeDefensePower", 0, int.MaxValue),
        new("storeLeaderOfSpot", 0, int.MaxValue),
        new("storeMasterOfUnit", 0, int.MaxValue),
        new("storeMemberOfUnit", 0, int.MaxValue),
        new("storePowerOfForce", 0, int.MaxValue),
        new("storeSpotOfBattle", 0, int.MaxValue),
        new("storeLeaderOfPower", 0, int.MaxValue),
        new("storeMasterOfPower", 0, int.MaxValue),
        new("storePowerOfAttack", 0, int.MaxValue),
        new("storeNonPlayerPower", 0, int.MaxValue),
        new("storePowerOfDefense", 0, int.MaxValue),
        new("storeRoamUnitOfSpot", 0, int.MaxValue),
        new("storeBaseClassOfUnit", 0, int.MaxValue),
    };
}
