namespace Wahren.AbstractSyntaxTree.TextTemplateHelper;

public struct ElementInfo
{
    public string Name;
    public string VariantType;
    public ReferenceKind ReferenceKind;
    public string[]? SpecialStringArray;

    public string CSharpableName => Name switch
    {
        "picture@cutin" => "picture_atmark_cutin",
        _ => Name,
    };

    public string Type => Helper.GetCorrespondingType(Name);

    public ElementInfo(string name, ReferenceKind referenceKind = ReferenceKind.Unknown, string variantType = nameof(Scenario))
    {
        this.Name = name;
        this.VariantType = variantType;
        this.ReferenceKind = referenceKind;
        this.SpecialStringArray = null;
    }

    internal static readonly ElementInfo[] Voice = new ElementInfo[]
    {
        new("voice_type", ReferenceKind.VoiceTypeReader),
        new("delskill", ReferenceKind.VoiceTypeReader),
        new("spot", ReferenceKind.Text),
        new("roam", ReferenceKind.Text),
        new("power", ReferenceKind.Text),
    };

    internal static readonly ElementInfo[] Workspace = System.Array.Empty<ElementInfo>();

    internal static readonly ElementInfo[] Story = new ElementInfo[]
    {
        new("friend", ReferenceKind.Scenario),
        new("fight", ReferenceKind.Boolean),
    };

    internal static readonly ElementInfo[] Event = new ElementInfo[]
    {
        new("disperse", ReferenceKind.Boolean),
        new("castle", ReferenceKind.Number),
        new("castle_battle", ReferenceKind.Boolean),
        new("personal_battle", ReferenceKind.Boolean),
        new("blind", ReferenceKind.Boolean | ReferenceKind.Number),
        new("w", ReferenceKind.Number),
        new("h", ReferenceKind.Number),
        new("bg", ReferenceKind.image),
        new("bcg", ReferenceKind.image),
        new("bgm", ReferenceKind.bgm),
        new("map", ReferenceKind.map),
        new("name", ReferenceKind.Text),
        new("color", ReferenceKind.Number),
        new("block"),
        new("limit", ReferenceKind.Number),
        new("title", ReferenceKind.Text),
        new("center"),
        new("italic"),
        new("handle", ReferenceKind.RedBlue),
        new("member"),
        new("second"),
        new("volume", ReferenceKind.Number),
        new("bg_fade"),
        new("dark_fade"),
        new("dark_alpha"),
        new("bg_interval"),
        new("dark_fade_e"),
        new("last_second"),
    };

    internal static readonly ElementInfo[] Dungeon = new ElementInfo[]
    {
        new("name", ReferenceKind.Text, "NumberScenario"),
        new("max", ReferenceKind.Number, "NumberScenario"),
        new("move_speed", ReferenceKind.Number, "NumberScenario"),
        new("prefix", ReferenceKind.Text, "NumberScenario"),
        new("suffix", ReferenceKind.Text, "NumberScenario"),
        new("lv_adjust", ReferenceKind.Number, "NumberScenario"),
        new("open", ReferenceKind.Boolean, "NumberScenario"),
        new("limit", ReferenceKind.Number, "NumberScenario"),
        new("bgm", ReferenceKind.bgm, "NumberScenario"),
        new("volume", ReferenceKind.Number, "NumberScenario"),
        new("blind", ReferenceKind.Number, "NumberScenario"),
        new("base_level", ReferenceKind.Number, "NumberScenario"),
        new("color", ReferenceKind.Number, "NumberScenario"),
        new("map", ReferenceKind.map, "NumberScenario"),
        new("floor", ReferenceKind.Field, "NumberScenario"),
        new("wall", ReferenceKind.Object, "NumberScenario"),
        new("start", ReferenceKind.Object, "NumberScenario"),
        new("goal", ReferenceKind.Object, "NumberScenario"),
        new("monster", ReferenceKind.Unit | ReferenceKind.Class, "NumberScenario"),
        new("monster_num", ReferenceKind.Number, "NumberScenario"),
        new("box", ReferenceKind.Object, "NumberScenario"),
        new("item"),
        new("item_num", ReferenceKind.Number, "NumberScenario"),
        new("item_text", ReferenceKind.Boolean, "NumberScenario"),
        new("home", ReferenceKind.Number, "NumberScenario"),
        new("ray", ReferenceKind.Number, "NumberScenario"),
    };

    internal static readonly ElementInfo[] Field = new ElementInfo[]
    {
        new("type", variantType: ""),
        new("attr", ReferenceKind.FieldAttributeTypeWriter, variantType: ""),
        new("color", ReferenceKind.Number, variantType: ""),
        new("id", ReferenceKind.FieldIdWriter, variantType: ""),
        new("edge", ReferenceKind.Boolean, variantType: ""),
        new("joint", variantType: ""),
        new("image", variantType: ""),
        new("add2", variantType: ""),
        new("member", variantType: ""),
        new("alt", ReferenceKind.Number, variantType: ""),
        new("alt_max", ReferenceKind.Number, variantType: ""),
        new("smooth", variantType: ""),
    };

    internal static readonly ElementInfo[] Movetype = new ElementInfo[]
    {
        new("name", ReferenceKind.Text, variantType: ""),
        new("help", ReferenceKind.Text, variantType: ""),
        new("consti", ReferenceKind.FieldAttributeTypeReader, variantType: ""),
    };

    internal static readonly ElementInfo[] Object = new ElementInfo[]
    {
        new("skill", variantType: ""),
        new("front", variantType: ""),
        new("width", ReferenceKind.Number, variantType: ""),
        new("height", ReferenceKind.Number, variantType: ""),
        new("alpha", ReferenceKind.Number, variantType: ""),
        new("type", ReferenceKind.Special, variantType: "") { SpecialStringArray = new[] { "coll", "wall", "wall2", "break", "break2", "gate", "floor" } },
        new("breakfire", ReferenceKind.Skill, variantType: ""),
        new("color", ReferenceKind.Number, variantType: ""),
        new("land_base", ReferenceKind.Boolean | ReferenceKind.Number, variantType: ""),
        new("no_stop", ReferenceKind.Boolean, variantType: ""),
        new("no_wall2", ReferenceKind.Number, variantType: ""),
        new("no_arc_hit", ReferenceKind.Boolean, variantType: ""),
        new("radius", ReferenceKind.Number, variantType: ""),
        new("blk", ReferenceKind.Boolean, variantType: ""),
        new("w", ReferenceKind.Number, variantType: ""),
        new("h", ReferenceKind.Number, variantType: ""),
        new("a", ReferenceKind.Number, variantType: ""),
        new("image", ReferenceKind.imagedata, variantType: ""),
        new("image2", ReferenceKind.imagedata, variantType: ""),
        new("image2_w", ReferenceKind.Number, variantType: ""),
        new("image2_h", ReferenceKind.Number, variantType: ""),
        new("image2_a", ReferenceKind.Number, variantType: ""),
        new("member", ReferenceKind.imagedata, variantType: ""),
        new("ground", ReferenceKind.Boolean, variantType: ""),
    };

    internal static readonly ElementInfo[] Race = new ElementInfo[]
    {
        new("name", ReferenceKind.Text),
        new("align", ReferenceKind.Number),
        new("brave", ReferenceKind.Number),
        new("consti", ReferenceKind.AttributeType),
        new("movetype", ReferenceKind.Movetype),
    };

    internal static readonly ElementInfo[] Skill = new ElementInfo[]
    {
        new("bright", ReferenceKind.Boolean, variantType: ""),
        new("func", ReferenceKind.Special, variantType: ""), // { SpecialStringArray = new[] { nameof(SkillKind.missile), nameof(SkillKind.sword), nameof(SkillKind.heal), nameof(SkillKind.summon), nameof(SkillKind.charge), nameof(SkillKind.status), } },
        new("name", ReferenceKind.Text, variantType: ""),
        new("icon", ReferenceKind.icon, variantType: ""),
        new("fkey", ReferenceKind.SkillGroupReader, variantType: ""),
        new("sortkey", ReferenceKind.Number, variantType: ""),
        new("special", ReferenceKind.Boolean | ReferenceKind.Number, variantType: ""),
        new("delay", ReferenceKind.Number, variantType: ""),
        new("gun_delay", ReferenceKind.Special, variantType: ""),
        new("quickreload", ReferenceKind.Boolean, variantType: ""),
        new("help", ReferenceKind.Text, variantType: ""),
        new("hide_help", ReferenceKind.Boolean, variantType: ""),
        new("sound", ReferenceKind.sound, variantType: ""),
        new("msg", ReferenceKind.Text, variantType: "Unit"),
        new("picture", ReferenceKind.picture, variantType: "Unit"),
        new("cutin", ReferenceKind.Special, variantType: "") { SpecialStringArray  = new[] { "type", "top", "y", "y2", "stop", "wake_time", "flash", "phantom", "alpha", "zoom", "inflate", "slide", "trans", } },
        new("value", ReferenceKind.Number, variantType: ""),
        new("talent", ReferenceKind.Boolean | ReferenceKind.Skill, variantType: ""),
        new("exp_per", ReferenceKind.Number | ReferenceKind.Boolean, variantType: ""),
        new("movetype", ReferenceKind.Special, variantType: ""), // { SpecialStringArray = new[] { "arc", "drop", "throw", "circle", "swing", } },
        new("type", ReferenceKind.Number, variantType: ""),
        new("color", ReferenceKind.Number, variantType: ""),
        new("w", ReferenceKind.Number, variantType: ""),
        new("h", ReferenceKind.Number, variantType: ""),
        new("a", ReferenceKind.Number, variantType: ""),
        new("mp", ReferenceKind.Number, variantType: ""),
        new("image", ReferenceKind.SpecialLate, variantType: ""),
        new("alpha_tip", ReferenceKind.Number, variantType: ""),
        new("alpha_butt", ReferenceKind.Number, variantType: ""),
        new("anime", ReferenceKind.Number, variantType: ""),
        new("anime_interval", ReferenceKind.Number, variantType: ""),
        new("center", ReferenceKind.Special, variantType: "") { SpecialStringArray = new[] { "off", "on", "end", } },
        new("ground", ReferenceKind.Number, variantType: ""),
        new("d360", ReferenceKind.Boolean, variantType: ""),
        new("d360_adj", ReferenceKind.Number, variantType: ""),
        new("rotate", ReferenceKind.Number, variantType: ""),
        new("direct", ReferenceKind.Special, variantType: "") { SpecialStringArray = new[] { "off", "on", "roll", }},
        new("resize_interval", ReferenceKind.Number, variantType: ""),
        new("resize_start", ReferenceKind.Number, variantType: ""),
        new("resize_reverse", ReferenceKind.Number, variantType: ""),
        new("resize_w", ReferenceKind.Number, variantType: ""),
        new("resize_w_start", ReferenceKind.Number, variantType: ""),
        new("resize_w_max", ReferenceKind.Number, variantType: ""),
        new("resize_w_min", ReferenceKind.Number, variantType: ""),
        new("resize_h_min", ReferenceKind.Number, variantType: ""),
        new("resize_h_max", ReferenceKind.Number, variantType: ""),
        new("resize_h_start", ReferenceKind.Number, variantType: ""),
        new("resize_h", ReferenceKind.Number, variantType: ""),
        new("resize_x", ReferenceKind.Number, variantType: ""),
        new("resize_x_start", ReferenceKind.Number, variantType: ""),
        new("resize_x_max", ReferenceKind.Number, variantType: ""),
        new("resize_x_min", ReferenceKind.Number, variantType: ""),
        new("resize_y_min", ReferenceKind.Number, variantType: ""),
        new("resize_y_max", ReferenceKind.Number, variantType: ""),
        new("resize_y_start", ReferenceKind.Number, variantType: ""),
        new("resize_y", ReferenceKind.Number, variantType: ""),
        new("resize_a", ReferenceKind.Number, variantType: ""),
        new("resize_s", ReferenceKind.Number, variantType: ""),
        new("resize_a_start", ReferenceKind.Number, variantType: ""),
        new("resize_s_start", ReferenceKind.Number, variantType: ""),
        new("resize_a_max", ReferenceKind.Number, variantType: ""),
        new("resize_s_max", ReferenceKind.Number, variantType: ""),
        new("resize_a_min", ReferenceKind.Number, variantType: ""),
        new("resize_s_min", ReferenceKind.Number, variantType: ""),
        new("force_fire", ReferenceKind.Boolean, variantType: ""),
        new("slow_per", ReferenceKind.Number, variantType: ""),
        new("slow_time", ReferenceKind.Number, variantType: ""),
        new("slide", ReferenceKind.Number, variantType: ""),
        new("slide_speed", ReferenceKind.Number, variantType: ""),
        new("slide_delay", ReferenceKind.Number, variantType: ""),
        new("slide_stamp", ReferenceKind.Number | ReferenceKind.Boolean, variantType: ""),
        new("wait_time", ReferenceKind.Number, variantType: ""),
        new("wait_time2", ReferenceKind.Number, variantType: ""),
        new("shake", ReferenceKind.Number | ReferenceKind.Boolean, variantType: ""),
        new("ray", ReferenceKind.Number, variantType: ""),
        new("force_ray", ReferenceKind.Boolean, variantType: ""),
        new("flash", ReferenceKind.Number, variantType: ""),
        new("flash_anime", ReferenceKind.Number, variantType: ""),
        new("flash_image", ReferenceKind.imagedata2, variantType: ""),
        new("collision", ReferenceKind.Skill, variantType: ""),
        new("afterdeath", ReferenceKind.Skill, variantType: ""),
        new("afterhit", ReferenceKind.Skill, variantType: ""),
        new("yorozu", ReferenceKind.SpecialLate, variantType: ""),
        new("str", ReferenceKind.Special, variantType: "") { SpecialStringArray = new[] { "none", "attack", "magic", "attack_magic", "attack_dext", "magic_dext", "fix", } },
        new("str_ratio", ReferenceKind.Number, variantType: ""),
        new("attr", ReferenceKind.SpecialLate, variantType: ""),
        new("add", ReferenceKind.SpecialLate, variantType: ""),
        new("add2", ReferenceKind.SpecialLate, variantType: ""),
        new("add_all", ReferenceKind.Boolean, variantType: ""),
        new("add_per", ReferenceKind.Number, variantType: ""),
        new("damage", ReferenceKind.Special | ReferenceKind.Number, variantType: "") { SpecialStringArray = new[] { "off", "pass", } },
        new("damage_range_adjust", ReferenceKind.Number, variantType: ""),
        new("attack_us", ReferenceKind.Number, variantType: ""),
        new("allfunc", ReferenceKind.Boolean, variantType: ""),
        new("bom", ReferenceKind.Boolean, variantType: ""),
        new("homing", ReferenceKind.SpecialLate, variantType: ""),
        new("homing2", ReferenceKind.Number, variantType: ""),
        new("forward", ReferenceKind.Boolean, variantType: ""),
        new("far", ReferenceKind.Boolean, variantType: ""),
        new("hard", ReferenceKind.Number, variantType: ""),
        new("hard2", ReferenceKind.Boolean | ReferenceKind.Number, variantType: ""),
        new("onehit", ReferenceKind.Boolean, variantType: ""),
        new("offset", ReferenceKind.SpecialLate, variantType: ""),
        new("offset_attr", ReferenceKind.Skill, variantType: ""),
        new("knock", ReferenceKind.Number, variantType: ""),
        new("knock_speed", ReferenceKind.Number, variantType: ""),
        new("knock_power", ReferenceKind.Number, variantType: ""),
        new("range", ReferenceKind.Number, variantType: ""),
        new("range_min", ReferenceKind.Number, variantType: ""),
        new("check", ReferenceKind.Number, variantType: ""),
        new("speed", ReferenceKind.Number, variantType: ""),
        new("wave", ReferenceKind.Special | ReferenceKind.Number, variantType: "") { SpecialStringArray = new[] { "on", "free", "interval", "hold", "fix", "max", "min", "rotate", } },
        new("origin", ReferenceKind.Boolean, variantType: ""),
        new("random_space", ReferenceKind.Number, variantType: ""),
        new("random_space_min", ReferenceKind.Number, variantType: ""),
        new("time", ReferenceKind.Number, variantType: ""),
        new("height", ReferenceKind.Number, variantType: ""),
        new("rush", ReferenceKind.Number, variantType: ""),
        new("rush_interval", ReferenceKind.Number, variantType: ""),
        new("rush_degree", ReferenceKind.Number, variantType: ""),
        new("rush_random_degree", ReferenceKind.Number, variantType: ""),
        new("follow", ReferenceKind.Number | ReferenceKind.Boolean, variantType: ""),
        new("start_degree", ReferenceKind.Number, variantType: ""),
        new("start_degree_fix", ReferenceKind.Number, variantType: ""),
        new("start_degree_turnunit", ReferenceKind.Boolean, variantType: ""),
        new("start_degree_type", ReferenceKind.Number, variantType: ""),
        new("start_random_degree", ReferenceKind.Number, variantType: ""),
        new("drop_degree", ReferenceKind.Number, variantType: ""),
        new("drop_degree2", ReferenceKind.Number, variantType: ""),
        new("joint_skill", ReferenceKind.Boolean, variantType: ""),
        new("send_target", ReferenceKind.Boolean, variantType: ""),
        new("send_image_degree", ReferenceKind.Boolean, variantType: ""),
        new("next", ReferenceKind.Skill, variantType: ""),
        new("next2", ReferenceKind.Skill, variantType: ""),
        new("next3", ReferenceKind.Skill, variantType: ""),
        new("next4", ReferenceKind.Skill, variantType: ""),
        new("next_order", ReferenceKind.Boolean, variantType: ""),
        new("next_last", ReferenceKind.Boolean, variantType: ""),
        new("next_first", ReferenceKind.Boolean, variantType: ""),
        new("next_interval", ReferenceKind.Number, variantType: ""),
        new("just_next", ReferenceKind.Skill, variantType: ""),
        new("pair_next", ReferenceKind.Skill, variantType: ""),
        new("item_type", ReferenceKind.Number, variantType: ""),
        new("item_sort", ReferenceKind.Number, variantType: ""),
        new("item_nosell", ReferenceKind.Boolean, variantType: ""),
        new("price", ReferenceKind.Number, variantType: ""),
        new("friend", ReferenceKind.Unit | ReferenceKind.Class, variantType: ""),
        new("summon_level", ReferenceKind.Number, variantType: ""),
    };

    internal static readonly ElementInfo[] Skillset = new ElementInfo[]
    {
        new("name", ReferenceKind.Text, variantType: ""),
        new("back", ReferenceKind.icon, variantType: ""),
        new("member", ReferenceKind.Skill, variantType: ""),
    };

    internal static readonly ElementInfo[] Spot = new ElementInfo[]
    {
        new("value", ReferenceKind.Number),
        new("politics", ReferenceKind.Special) { SpecialStringArray = new[] { "on", } },
        new("merce", ReferenceKind.Unit | ReferenceKind.Class),
        new("name", ReferenceKind.Text),
        new("image", ReferenceKind.imagedata),
        new("x", ReferenceKind.Number),
        new("y", ReferenceKind.Number),
        new("w", ReferenceKind.Number),
        new("h", ReferenceKind.Number),
        new("big", ReferenceKind.Number),
        new("color", ReferenceKind.Number),
        new("map", ReferenceKind.map),
        new("castle_battle", ReferenceKind.Boolean),
        new("yorozu", ReferenceKind.Class),
        new("limit", ReferenceKind.Number),
        new("bgm", ReferenceKind.bgm),
        new("volume", ReferenceKind.Number),
        new("gain", ReferenceKind.Number),
        new("castle", ReferenceKind.Number),
        new("capacity", ReferenceKind.Number),
        new("monster", ReferenceKind.Unit | ReferenceKind.Class),
        new("member", ReferenceKind.Unit | ReferenceKind.Class),
        new("dungeon", ReferenceKind.Dungeon),
        new("no_home", ReferenceKind.Boolean),
        new("no_raise", ReferenceKind.Boolean),
        new("castle_lot", ReferenceKind.Number),
        new("text", ReferenceKind.Text),
    };

    internal static readonly ElementInfo[] UnitFallthroughClass = new ElementInfo[]
    {
        new("troop_sort", ReferenceKind.Number),
        new("stealth", ReferenceKind.Number),
        new("free_move", ReferenceKind.Number),
        new("name", ReferenceKind.Text),
        new("help", ReferenceKind.Text),
        new("sex", ReferenceKind.Special) { SpecialStringArray = new[] { "neuter", "male", "female", } },
        new("a", ReferenceKind.Number),
        new("h", ReferenceKind.Number),
        new("w", ReferenceKind.Number),
        new("text", ReferenceKind.Text),
        new("sub_image_even", ReferenceKind.Boolean),
        new("yorozu", ReferenceKind.Special) { SpecialStringArray = new[] { "keep_direct", "no_circle", "base", "keep_color", } },
        new("radius", ReferenceKind.Number),
        new("radius_press", ReferenceKind.Number),
        new("no_escape", ReferenceKind.Boolean),
        new("no_regular", ReferenceKind.Boolean),
        new("no_knock", ReferenceKind.Boolean | ReferenceKind.Number),
        new("no_cover", ReferenceKind.Boolean),
        new("dead_event", ReferenceKind.Event),
        new("beast_unit", ReferenceKind.Boolean),
        new("summon_max", ReferenceKind.Number),
        new("summon_level", ReferenceKind.Number),
        new("attack_range", ReferenceKind.Number),
        new("escape_range", ReferenceKind.Number),
        new("escape_run", ReferenceKind.Number),
        new("hand_range", ReferenceKind.Number),
        new("wake_range", ReferenceKind.Number),
        new("view_range", ReferenceKind.Number),
        new("cavalry_range", ReferenceKind.Number),
        new("view_unit", ReferenceKind.Boolean),
        new("force_view_unit", ReferenceKind.Boolean),
        new("force_blind_unit", ReferenceKind.Boolean),
        new("satellite", ReferenceKind.Boolean | ReferenceKind.Number),
        new("hasexp", ReferenceKind.Number),
        new("brave", ReferenceKind.Boolean | ReferenceKind.Number),
        new("level", ReferenceKind.Number),
        new("hp", ReferenceKind.Number),
        new("mp", ReferenceKind.Number),
        new("attack", ReferenceKind.Number),
        new("defense", ReferenceKind.Number),
        new("magic", ReferenceKind.Number),
        new("magdef", ReferenceKind.Number),
        new("speed", ReferenceKind.Number),
        new("dext", ReferenceKind.Number),
        new("move", ReferenceKind.Number),
        new("hprec", ReferenceKind.Number),
        new("mprec", ReferenceKind.Number),
        new("heal_max", ReferenceKind.Number),
        new("attack_max", ReferenceKind.Number),
        new("defense_max", ReferenceKind.Number),
        new("magic_max", ReferenceKind.Number),
        new("magdef_max", ReferenceKind.Number),
        new("speed_max", ReferenceKind.Number),
        new("dext_max", ReferenceKind.Number),
        new("move_max", ReferenceKind.Number),
        new("hprec_max", ReferenceKind.Number),
        new("mprec_max", ReferenceKind.Number),
        new("movetype", ReferenceKind.Movetype),
        new("hpUp", ReferenceKind.Number),
        new("mpUp", ReferenceKind.Number),
        new("attackUp", ReferenceKind.Number),
        new("defenseUp", ReferenceKind.Number),
        new("magicUp", ReferenceKind.Number),
        new("magdefUp", ReferenceKind.Number),
        new("speedUp", ReferenceKind.Number),
        new("dextUp", ReferenceKind.Number),
        new("moveUp", ReferenceKind.Number),
        new("hprecUp", ReferenceKind.Number),
        new("mprecUp", ReferenceKind.Number),
        new("hpMax", ReferenceKind.Number),
        new("mpMax", ReferenceKind.Number),
        new("attackMax", ReferenceKind.Number),
        new("defenseMax", ReferenceKind.Number),
        new("magicMax", ReferenceKind.Number),
        new("magdefMax", ReferenceKind.Number),
        new("speedMax", ReferenceKind.Number),
        new("dextMax", ReferenceKind.Number),
        new("moveMax", ReferenceKind.Number),
        new("hprecMax", ReferenceKind.Number),
        new("mprecMax", ReferenceKind.Number),
        new("race", ReferenceKind.Race),
        new("sortkey",  referenceKind: ReferenceKind.Number),
        new("picture", ReferenceKind.picture),
        new("picture_detail", ReferenceKind.Special) { SpecialStringArray = new[] { "off", "on", "on1", "on2", "on3", } },
        new("picture_menu",  referenceKind: ReferenceKind.Number),
        new("picture_floor", ReferenceKind.Special) { SpecialStringArray = new[] { "top", "msg", "base", "bottom", } },
        new("picture_shift",  referenceKind: ReferenceKind.Number),
        new("picture_shift_up",  referenceKind: ReferenceKind.Number),
        new("picture_center",  referenceKind: ReferenceKind.Number),
        new("picture_back"),
        new("price", ReferenceKind.Number),
        new("cost", ReferenceKind.Number),
        new("finance", ReferenceKind.Number),
        new("tkool", ReferenceKind.Boolean),
        new("keep_form", ReferenceKind.Boolean | ReferenceKind.Number),
        new("breast_width", ReferenceKind.Number),
        new("medical", ReferenceKind.Number),
        new("active", ReferenceKind.Special) { SpecialStringArray = new[] { "never", "rect", "range", "time", "troop", "never2", "rect2", "range2", "time2", "troop2", } },
        new("activenum"),
        new("handle", ReferenceKind.Boolean),
        new("red", ReferenceKind.Boolean),
        new("rank_text", ReferenceKind.Text),
        new("no_training", ReferenceKind.Boolean),
        new("force_voice", ReferenceKind.Boolean),
        new("face", ReferenceKind.face),
        new("same_friend", ReferenceKind.Boolean),
        new("same_call", ReferenceKind.Boolean),
        new("member", ReferenceKind.Unit | ReferenceKind.Class),
        new("level_max", ReferenceKind.Number),
        new("exp", ReferenceKind.Number),
        new("exp_mul", ReferenceKind.Number),
        new("exp_max", ReferenceKind.Number),
        new("line", ReferenceKind.Special) { SpecialStringArray = new[] { "back", "front", } },
        new("image", ReferenceKind.imagedata),
        new("sub_image", ReferenceKind.imagedata, variantType: "Special_sub_image"),
        new("politics", ReferenceKind.Special) { SpecialStringArray = new[] { "on", "fix", "erase", "unique", } },
        new("element_lost", ReferenceKind.Boolean),
        new("fkey", ReferenceKind.ClassTypeWriter),
        new("friend", ReferenceKind.SpecialLate),
        new("merce", ReferenceKind.Unit | ReferenceKind.Class),
        new("consti", ReferenceKind.AttributeType),
        new("multi", ReferenceKind.Status | ReferenceKind.Number),
        new("lost_corpse", ReferenceKind.Number),
        new("add_vassal", ReferenceKind.Special) { SpecialStringArray = new[] { "off", "on", "roam", } },
        new("value", ReferenceKind.Number),
        new("break", ReferenceKind.Skill),
        new("scream", ReferenceKind.sound),
        new("skill", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("skill2", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("learn", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("delskill", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("delskill2", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("item", ReferenceKind.Skill),
        new("leader_skill", ReferenceKind.Skill | ReferenceKind.Skillset),
        new("assist_skill", ReferenceKind.Skill | ReferenceKind.Skillset),
    };

    internal static readonly ElementInfo[] Unit = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(UnitFallthroughClass, new ElementInfo[]
    {
        new("talent", ReferenceKind.Boolean),
        new("class", ReferenceKind.Class),
        new("bgm", ReferenceKind.bgm),
        new("volume", ReferenceKind.Number),
        new("alive_per", ReferenceKind.Number),
        new("yabo", ReferenceKind.Number),
        new("kosen", ReferenceKind.Number),
        new("align", ReferenceKind.Number),
        new("loyal", ReferenceKind.Unit),
        new("power_name", ReferenceKind.Text),
        new("enemy", ReferenceKind.Unit),
        new("flag", ReferenceKind.flag),
        new("staff", ReferenceKind.Race | ReferenceKind.Class),
        new("diplomacy", ReferenceKind.Boolean),
        new("castle_guard", ReferenceKind.Unit | ReferenceKind.Class),
        new("actor", ReferenceKind.Boolean),
        new("enable", ReferenceKind.Number),
        new("enable_select", ReferenceKind.Boolean),
        new("enable_max", ReferenceKind.Number),
        new("fix", ReferenceKind.Special) { SpecialStringArray = new[] { "off", "on", "home", } },
        new("home", ReferenceKind.Spot),
        new("noremove_unit", ReferenceKind.Boolean),
        new("noemploy_unit", ReferenceKind.Boolean),
        new("noitem_unit", ReferenceKind.Boolean),
        new("arbeit", ReferenceKind.Special | ReferenceKind.Number) { SpecialStringArray = new[] { "off", "on", "power", "fix", } },
        new("arbeit_capacity", ReferenceKind.Number),
        new("join", ReferenceKind.Text),
        new("dead", ReferenceKind.Text),
        new("retreat", ReferenceKind.Text),
        new("voice_type", ReferenceKind.VoiceTypeWriter),
    }));

    internal static readonly ElementInfo[] Class = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(UnitFallthroughClass, new ElementInfo[]
    {
        new("image2", ReferenceKind.imagedata),
        new("sub_image2", ReferenceKind.imagedata),
        new("unique", ReferenceKind.Boolean),
        new("same_sex", ReferenceKind.Boolean),
        new("change", ReferenceKind.Class),
        new("friend_ex", ReferenceKind.Race | ReferenceKind.Class | ReferenceKind.Unit),
        // new("samecall_baseup"),
    }));

    internal static readonly ElementInfo[] Power = new ElementInfo[]
    {
        new("castle_battle", ReferenceKind.Boolean),
        new("event", ReferenceKind.Boolean),
        new("name", ReferenceKind.Text),
        new("help", ReferenceKind.Text),
        new("master", ReferenceKind.Unit),
        new("flag", ReferenceKind.flag),
        new("bgm", ReferenceKind.bgm),
        new("volume", ReferenceKind.Number),
        new("diplomacy", ReferenceKind.Boolean),
        new("enable_select", ReferenceKind.Boolean),
        new("enable_talent", ReferenceKind.Boolean),
        new("free_raise", ReferenceKind.Boolean),
        new("money", ReferenceKind.Number),
        new("home", ReferenceKind.Spot),
        new("fix", ReferenceKind.Special) { SpecialStringArray = new[] { "off", "on", "home", "hold", "warlike", "freeze", } },
        new("diplo", ReferenceKind.Power),
        new("league", ReferenceKind.Power),
        new("enemy_power", ReferenceKind.Power),
        new("staff", ReferenceKind.Unit | ReferenceKind.Class | ReferenceKind.Race),
        new("merce", ReferenceKind.Unit | ReferenceKind.Class | ReferenceKind.Race),
        new("training_average", ReferenceKind.Number),
        new("base_merits", ReferenceKind.Number),
        new("merits", ReferenceKind.Unit),
        new("base_loyal", ReferenceKind.Number),
        new("loyals", ReferenceKind.Unit),
        new("head", ReferenceKind.Text),
        new("head2", ReferenceKind.Text),
        new("head3", ReferenceKind.Text),
        new("head4", ReferenceKind.Text),
        new("head5", ReferenceKind.Text),
        new("head6", ReferenceKind.Text),
        new("diff", ReferenceKind.Text),
        new("yabo", ReferenceKind.Number),
        new("kosen", ReferenceKind.Number),
        new("text", ReferenceKind.Text),
        new("member", ReferenceKind.Spot),
        new("friend", ReferenceKind.Scenario),
        new("master2", ReferenceKind.Text),
        new("master3", ReferenceKind.Text),
        new("master4", ReferenceKind.Text),
        new("master5", ReferenceKind.Text),
        new("master6", ReferenceKind.Text),
        new("enable"),
        new("training_up", ReferenceKind.Number),
    };

    internal static readonly ElementInfo[] Scenario = new ElementInfo[]
    {
        new("ws_red", ReferenceKind.Number, ""),
        new("ws_blue", ReferenceKind.Number, ""),
        new("ws_green", ReferenceKind.Number, ""),
        new("ws_alpha", ReferenceKind.Number, ""),
        new("ws_light", ReferenceKind.Number, ""),
        new("ws_light_range", ReferenceKind.Number, ""),
        new("discus", variantType: ""),
        new("save_name", ReferenceKind.Text, ""),
        new("enable_select", ReferenceKind.Boolean, ""),
        new("max_unit", ReferenceKind.Number, ""),
        new("blind", ReferenceKind.Number, ""),
        new("name", ReferenceKind.Text, ""),
        new("map", ReferenceKind.image, ""),
        new("help", ReferenceKind.Text, ""),
        new("locate_x", ReferenceKind.Number, ""),
        new("locate_y", ReferenceKind.Number, ""),
        new("begin_text", ReferenceKind.Text, ""),
        new("world", ReferenceKind.Event, ""),
        new("fight", ReferenceKind.Event, ""),
        new("politics", ReferenceKind.Event, ""),
        new("war_capacity", ReferenceKind.Number, ""),
        new("spot_capacity", ReferenceKind.Number, ""),
        new("gain_per", ReferenceKind.Number, ""),
        new("support_range", ReferenceKind.Number, ""),
        new("my_range", ReferenceKind.Number, ""),
        new("myhelp_range", ReferenceKind.Number, ""),
        new("base_level", ReferenceKind.Number, ""),
        new("monster_level", ReferenceKind.Number, ""),
        new("training_up", ReferenceKind.Number, ""),
        new("actor_per", ReferenceKind.Number, ""),
        new("sortkey", ReferenceKind.Number, ""),
        new("default_ending", ReferenceKind.Boolean, ""),
        new("power_order", ReferenceKind.Special, "") { SpecialStringArray = new[] { "normal", "test", "dash", } },
        new("enable", ReferenceKind.Boolean, ""),
        new("enable_talent", ReferenceKind.Boolean, ""),
        new("party", ReferenceKind.Boolean, ""),
        new("no_autosave", ReferenceKind.Boolean, ""),
        new("zone", ReferenceKind.Text, ""),
        new("nozone", ReferenceKind.Boolean, ""),
        new("item0", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item1", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item2", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item3", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item4", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item5", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item6", ReferenceKind.Boolean | ReferenceKind.Number, ""),
        new("item_limit", ReferenceKind.Boolean, ""),
        new("poli", variantType: ""),
        new("camp", variantType: ""),
        new("multi", variantType: ""),
        new("item", variantType: ""),
        new("item_sale", ReferenceKind.Skill, ""),
        new("item_hold", ReferenceKind.Skill, ""),
        new("text", ReferenceKind.Text, ""),
        new("roam", ReferenceKind.Unit, ""),
        new("spot", ReferenceKind.Spot, ""),
        new("power", ReferenceKind.Power, ""),
        new("offset", variantType: ""),
    };

    public static readonly ElementInfo[] Discards = new ElementInfo[] {
        new("str"),
        new("fkey"),
        new("loyal"),
        new("brave"),
        new("arbeit"),
        new("change"),
        new("ground"),
        new("gun_delay"),
        new("text"),
        new("icon"),
        new("wave"),
        new("cutin"),
        new("diplo"),
        new("consti"),
        new("league"),
        new("loyals"),
        new("merits"),
        new("yorozu"),
        new("enemy_power"),
        new("leader_skill"),
        new("assist_skill"),
        new("roam"),
        new("spot"),
        new("power"),
        new("add2"),
        new("item"),
        new("merce"),
        new("next2"),
        new("next3"),
        new("sound"),
        new("member"),
        new("monster"),
        new("item_hold"),
        new("item_sale"),
        new("just_next"),
        new("castle_guard"),
        new("enemy"),
        new("staff"),
        new("friend"),
        new("offset"),
        new("delskill"),
        new("delskill2"),
        new("voice_type"),
        new("ray"),
        new("poli"),
        new("camp"),
        new("home"),
        new("multi"),
        new("learn"),
        new("color"),
        new("joint"),
        new("skill"),
        new("skill2"),
        new("weapon"),
        new("weapon2"),
        new("activenum"),
        new("friend_ex"),
    };
}
