namespace Wahren.AbstractSyntaxTree.TextTemplateHelper;

public struct ElementInfo
{
    public string name;
    public string variantType;
    public ElementContentType elementContentType;

    public ElementInfo(string name, string variantType = nameof(Scenario), ElementContentType elementContentType = ElementContentType.Unknown)
    {
        this.name = name;
        this.variantType = variantType;
        this.elementContentType = elementContentType;
    }

    public static bool IsAllScenarioVariant(string name) => name switch
    {
        nameof(Dungeon) or nameof(Skill) => false,
        _ => true,
    };

    public static ElementInfo[] Get(string name)
    {
        switch (name)
        {
            case nameof(Power): return Power;
            case nameof(Class): return Class;
            case nameof(Dungeon): return Dungeon;
            case nameof(Field): return Field;
            case nameof(Movetype): return Movetype;
            case nameof(Object): return Object;
            case nameof(Race): return Race;
            case nameof(Skill): return Skill;
            case nameof(Skillset): return Skillset;
            case nameof(Spot): return Spot;
            case nameof(Unit): return Unit;
            case nameof(Scenario): return Scenario;
            case nameof(Event): return Event;
            case nameof(Story): return Story;
            default: return System.Array.Empty<ElementInfo>();
        }
    }

    internal static readonly ElementInfo[] Workspace = System.Array.Empty<ElementInfo>();

    internal static readonly ElementInfo[] Story = new ElementInfo[]
    {
        new("friend", elementContentType: ElementContentType.Scenario),
        new("fight", elementContentType: ElementContentType.Boolean),
    };

    internal static readonly ElementInfo[] Event = new ElementInfo[]
    {
        new("disperse", elementContentType: ElementContentType.Boolean),
        new("castle"),
        new("castle_battle"),
        new("blind"),
        new("w", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("bg"),
        new("bcg"),
        new("bgm"),
        new("map"),
        new("name", elementContentType: ElementContentType.Text),
        new("size"),
        new("color"),
        new("block"),
        new("limit"),
        new("title", elementContentType: ElementContentType.Text),
        new("center"),
        new("italic"),
        new("handle"),
        new("member"),
        new("second"),
        new("volume"),
        new("bg_fade"),
        new("dark_fade"),
        new("dark_alpha"),
        new("bg_interval"),
        new("dark_fade_e"),
        new("last_second"),
    };

    internal static readonly ElementInfo[] Dungeon = new ElementInfo[]
    {
        new("name", elementContentType: ElementContentType.Text),
        new("max"),
        new("move_speed", elementContentType: ElementContentType.Number),
        new("prefix", elementContentType: ElementContentType.Text),
        new("suffix", elementContentType: ElementContentType.Text),
        new("lv_adjust"),
        new("open"),
        new("limit", elementContentType: ElementContentType.Number),
        new("bgm"),
        new("volume"),
        new("blind"),
        new("base_level"),
        new("color"),
        new("map"),
        new("floor"),
        new("wall"),
        new("start"),
        new("goal"),
        new("monster"),
        new("monster_num"),
        new("box"),
        new("item"),
        new("item_num"),
        new("item_text"),
        new("home"),
        new("ray"),
    };

    internal static readonly ElementInfo[] Field = new ElementInfo[]
    {
        new("type"),
        new("attr"),
        new("color"),
        new("id"),
        new("edge"),
        new("joint"),
        new("image"),
        new("add2"),
        new("member"),
        new("alt"),
        new("alt_max"),
        new("smooth"),
    };

    internal static readonly ElementInfo[] Movetype = new ElementInfo[]
    {
        new("name", elementContentType: ElementContentType.Text),
        new("help", elementContentType: ElementContentType.Text),
        new("consti"),
    };

    internal static readonly ElementInfo[] Object = new ElementInfo[]
    {
        new("skill"),
        new("front"),
        new("width"),
        new("height"),
        new("alpha"),
        new("type"),
        new("breakfire"),
        new("land_base"),
        new("no_stop"),
        new("no_wall2"),
        new("no_arc_hit"),
        new("radius"),
        new("blk"),
        new("w", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("a", elementContentType: ElementContentType.Number),
        new("image"),
        new("image2"),
        new("image2_w", elementContentType: ElementContentType.Number),
        new("image2_h", elementContentType: ElementContentType.Number),
        new("image2_a", elementContentType: ElementContentType.Number),
        new("member"),
        new("ground"),
    };

    internal static readonly ElementInfo[] Race = new ElementInfo[]
    {
        new("name", elementContentType: ElementContentType.Text),
        new("align", elementContentType: ElementContentType.Number),
        new("brave", elementContentType: ElementContentType.Number),
        new("consti"),
        new("movetype", elementContentType: ElementContentType.Movetype),
    };

    internal static readonly ElementInfo[] Skill = new ElementInfo[]
    {
        new("force_ray"),
        new("bright"),
        new("func"),
        new("name", elementContentType: ElementContentType.Text),
        new("icon"),
        new("fkey"),
        new("sortkey", elementContentType: ElementContentType.Number),
        new("special"),
        new("delay"),
        new("gun_delay"),
        new("quickreload"),
        new("help", elementContentType: ElementContentType.Text),
        new("hide_help"),
        new("sound"),
        new("msg", variantType: "Unit", elementContentType: ElementContentType.Text),
        new("picture", variantType: "Unit"),
        new("cutin"),
        new("value"),
        new("talent"),
        new("exp_per"),
        new("movetype"),
        new("type"),
        new("color"),
        new("w", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("a", elementContentType: ElementContentType.Number),
        new("mp"),
        new("image"),
        new("alpha_tip"),
        new("alpha_butt"),
        new("anime"),
        new("anime_interval"),
        new("center"),
        new("ground"),
        new("d360"),
        new("d360_adj"),
        new("rotate"),
        new("direct"),
        new("resize_interval"),
        new("resize_start"),
        new("resize_reverse"),
        new("resize_w"),
        new("resize_w_start"),
        new("resize_w_max"),
        new("resize_w_min"),
        new("resize_h_min"),
        new("resize_h_max"),
        new("resize_h_start"),
        new("resize_h"),
        new("resize_x"),
        new("resize_x_start"),
        new("resize_x_max"),
        new("resize_x_min"),
        new("resize_y_min"),
        new("resize_y_max"),
        new("resize_y_start"),
        new("resize_y"),
        new("resize_a"),
        new("resize_s"),
        new("resize_a_start"),
        new("resize_s_start"),
        new("resize_a_max"),
        new("resize_s_max"),
        new("resize_a_min"),
        new("resize_s_min"),
        new("force_fire"),
        new("slow_per"),
        new("slow_time"),
        new("slide"),
        new("slide_speed"),
        new("slide_delay"),
        new("slide_stamp"),
        new("wait_time"),
        new("wait_time2"),
        new("shake"),
        new("ray"),
        new("flash"),
        new("flash_anime"),
        new("flash_image"),
        new("collision"),
        new("afterdeath"),
        new("afterhit"),
        new("yorozu"),
        new("str"),
        new("str_ratio"),
        new("attr"),
        new("add"),
        new("add2"),
        new("add_all"),
        new("add_per"),
        new("damage"),
        new("damage_range_adjust"),
        new("attack_us"),
        new("allfunc"),
        new("bom"),
        new("homing"),
        new("homing2"),
        new("forward"),
        new("far"),
        new("hard"),
        new("hard2"),
        new("onehit"),
        new("offset"),
        new("offset_attr"),
        new("knock"),
        new("knock_speed"),
        new("knock_power"),
        new("range"),
        new("range_min"),
        new("check"),
        new("speed"),
        new("wave"),
        new("origin"),
        new("random_space"),
        new("random_space_min"),
        new("time"),
        new("height"),
        new("rush"),
        new("rush_interval"),
        new("rush_degree"),
        new("rush_random_degree"),
        new("follow"),
        new("start_degree"),
        new("start_degree_fix"),
        new("start_degree_turnunit"),
        new("start_degree_type"),
        new("start_random_degree"),
        new("drop_degree"),
        new("drop_degree2"),
        new("joint_skill"),
        new("send_target"),
        new("send_image_degree"),
        new("next"),
        new("next2"),
        new("next3"),
        new("next4"),
        new("next_order"),
        new("next_last"),
        new("next_first"),
        new("next_interval"),
        new("just_next"),
        new("pair_next"),
        new("item_type"),
        new("item_sort"),
        new("item_nosell"),
        new("price"),
        new("friend"),
        new("summon_level"),
    };

    internal static readonly ElementInfo[] Skillset = new ElementInfo[]
    {
        new("name", elementContentType: ElementContentType.Text),
        new("back"),
        new("member", elementContentType: ElementContentType.Skill),
    };

    internal static readonly ElementInfo[] Spot = new ElementInfo[]
    {
        new("value", elementContentType: ElementContentType.Number),
        new("politics"),
        new("merce"),
        new("name", elementContentType: ElementContentType.Text),
        new("image"),
        new("x", elementContentType: ElementContentType.Number),
        new("y", elementContentType: ElementContentType.Number),
        new("w", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("big"),
        new("map"),
        new("castle_battle", elementContentType: ElementContentType.Boolean),
        new("yorozu"),
        new("limit", elementContentType: ElementContentType.Number),
        new("bgm"),
        new("volume"),
        new("gain", elementContentType: ElementContentType.Number),
        new("castle", elementContentType: ElementContentType.Number),
        new("capacity", elementContentType: ElementContentType.Number),
        new("monster", elementContentType: ElementContentType.Unit | ElementContentType.Class),
        new("member", elementContentType: ElementContentType.Unit | ElementContentType.Class),
        new("dungeon", elementContentType: ElementContentType.Dungeon),
        new("no_home"),
        new("no_raise"),
        new("castle_lot", elementContentType: ElementContentType.Number),
        new("text", elementContentType: ElementContentType.Text),
    };

    internal static readonly ElementInfo[] Unit = new ElementInfo[]
    {
        new("dead_event", elementContentType: ElementContentType.Event),
        new("troop_sort"),
        new("no_regular"),
        new("stealth"),
        new("name", elementContentType: ElementContentType.Text),
        new("help", elementContentType: ElementContentType.Text),
        new("sex"),
        new("talent"),
        new("race", elementContentType: ElementContentType.Race),
        new("class", elementContentType: ElementContentType.Class),
        new("radius"),
        new("radius_press"),
        new("w", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("a", elementContentType: ElementContentType.Number),
        new("image"),
        new("tkool"),
        new("face"),
        new("bgm"),
        new("volume"),
        new("picture"),
        new("picture@cutin"),
        new("picture_detail"),
        new("picture_menu"),
        new("picture_floor"),
        new("picture_shift"),
        new("picture_shift_up"),
        new("picture_center"),
        new("picture_back"),
        new("price"),
        new("cost"),
        new("finance"),
        new("hasexp"),
        new("alive_per"),
        new("medical"),
        new("friend"),
        new("merce"),
        new("same_friend"),
        new("same_call"),
        new("member"),
        new("level", elementContentType: ElementContentType.Number),
        new("hp", elementContentType: ElementContentType.Number),
        new("mp", elementContentType: ElementContentType.Number),
        new("attack", elementContentType: ElementContentType.Number),
        new("defense", elementContentType: ElementContentType.Number),
        new("magic", elementContentType: ElementContentType.Number),
        new("magdef", elementContentType: ElementContentType.Number),
        new("speed", elementContentType: ElementContentType.Number),
        new("dext", elementContentType: ElementContentType.Number),
        new("move", elementContentType: ElementContentType.Number),
        new("hprec", elementContentType: ElementContentType.Number),
        new("mprec", elementContentType: ElementContentType.Number),
        new("summon_max", elementContentType: ElementContentType.Number),
        new("summon_level", elementContentType: ElementContentType.Number),
        new("heal_max", elementContentType: ElementContentType.Number),
        new("attack_max", elementContentType: ElementContentType.Number),
        new("defense_max", elementContentType: ElementContentType.Number),
        new("magic_max", elementContentType: ElementContentType.Number),
        new("magdef_max", elementContentType: ElementContentType.Number),
        new("speed_max", elementContentType: ElementContentType.Number),
        new("dext_max", elementContentType: ElementContentType.Number),
        new("move_max", elementContentType: ElementContentType.Number),
        new("hprec_max", elementContentType: ElementContentType.Number),
        new("mprec_max", elementContentType: ElementContentType.Number),
        new("leader_skill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("assist_skill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("skill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("skill2", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("delskill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("delskill2", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("learn", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("consti", elementContentType: ElementContentType.AttributeType),
        new("movetype", elementContentType: ElementContentType.Movetype),
        new("line"),
        new("satellite"),
        new("beast_unit"),
        new("no_knock"),
        new("no_cover"),
        new("view_unit"),
        new("element_lost"),
        new("attack_range", elementContentType: ElementContentType.Number),
        new("escape_range", elementContentType: ElementContentType.Number),
        new("escape_run", elementContentType: ElementContentType.Number),
        new("hand_range", elementContentType: ElementContentType.Number),
        new("wake_range", elementContentType: ElementContentType.Number),
        new("view_range", elementContentType: ElementContentType.Number),
        new("cavalry_range", elementContentType: ElementContentType.Number),
        new("level_max", elementContentType: ElementContentType.Number),
        new("multi"),
        new("exp", elementContentType: ElementContentType.Number),
        new("exp_mul", elementContentType: ElementContentType.Number),
        new("exp_max", elementContentType: ElementContentType.Number),
        new("hpUp", elementContentType: ElementContentType.Number),
        new("mpUp", elementContentType: ElementContentType.Number),
        new("attackUp", elementContentType: ElementContentType.Number),
        new("defenseUp", elementContentType: ElementContentType.Number),
        new("magicUp", elementContentType: ElementContentType.Number),
        new("magdefUp", elementContentType: ElementContentType.Number),
        new("speedUp", elementContentType: ElementContentType.Number),
        new("dextUp", elementContentType: ElementContentType.Number),
        new("moveUp", elementContentType: ElementContentType.Number),
        new("hprecUp", elementContentType: ElementContentType.Number),
        new("mprecUp", elementContentType: ElementContentType.Number),
        new("hpMax", elementContentType: ElementContentType.Number),
        new("mpMax", elementContentType: ElementContentType.Number),
        new("attackMax", elementContentType: ElementContentType.Number),
        new("defenseMax", elementContentType: ElementContentType.Number),
        new("magicMax", elementContentType: ElementContentType.Number),
        new("magdefMax", elementContentType: ElementContentType.Number),
        new("speedMax", elementContentType: ElementContentType.Number),
        new("dextMax", elementContentType: ElementContentType.Number),
        new("moveMax", elementContentType: ElementContentType.Number),
        new("hprecMax", elementContentType: ElementContentType.Number),
        new("mprecMax", elementContentType: ElementContentType.Number),
        new("fkey", elementContentType: ElementContentType.Number),
        new("yabo", elementContentType: ElementContentType.Number),
        new("kosen", elementContentType: ElementContentType.Number),
        new("brave", elementContentType: ElementContentType.Number),
        new("align", elementContentType: ElementContentType.Number),
        new("enemy", elementContentType: ElementContentType.Number),
        new("loyal", elementContentType: ElementContentType.Number),
        new("power_name", elementContentType: ElementContentType.Text),
        new("flag"),
        new("staff"),
        new("diplomacy"),
        new("castle_guard"),
        new("actor"),
        new("sortkey"),
        new("enable"),
        new("enable_select"),
        new("enable_max"),
        new("fix"),
        new("home", elementContentType: ElementContentType.Spot),
        new("item"),
        new("no_training"),
        new("no_escape"),
        new("noremove_unit"),
        new("noemploy_unit"),
        new("noitem_unit"),
        new("arbeit"),
        new("arbeit_capacity"),
        new("join"),
        new("dead"),
        new("retreat"),
        new("scream"),
        new("break"),
        new("lost_corpse"),
        new("add_vassal"),
        new("politics"),
        new("force_voice"),
        new("voice_type", elementContentType: ElementContentType.VoiceType),
        new("value"),
        new("handle"),
        new("red"),
        new("active"),
        new("sub_image"),
        new("sub_image_even"),
        new("yorozu"),
        new("activenum"),
        new("breast_width"),
        new("rank_text"),
        new("keep_form"),
        new("text", elementContentType: ElementContentType.Text),
    };

    internal static readonly ElementInfo[] Class = new ElementInfo[]
    {
        new("no_regular"),
        new("stealth"),
        new("troop_sort"),
        new("medical", elementContentType: ElementContentType.Number),
        new("politics"),
        new("keep_form"),
        new("a", elementContentType: ElementContentType.Number),
        new("h", elementContentType: ElementContentType.Number),
        new("w", elementContentType: ElementContentType.Number),
        new("sex"),
        new("exp", elementContentType: ElementContentType.Number),
        new("help", elementContentType: ElementContentType.Text),
        new("name", elementContentType: ElementContentType.Text),
        new("cost", elementContentType: ElementContentType.Number),
        new("face"),
        new("race", elementContentType: ElementContentType.Race),
        new("tkool"),
        new("image"),
        new("break"),
        new("price", elementContentType: ElementContentType.Number),
        new("picture"),
        new("picture@cutin"),
        new("picture_detail"),
        new("picture_menu"),
        new("picture_floor"),
        new("picture_shift"),
        new("picture_shift_up"),
        new("image2"),
        new("scream"),
        new("hasexp"),
        new("unique"),
        new("radius"),
        new("radius_press"),
        new("same_sex"),
        new("same_friend"),
        new("same_call"),
        new("level", elementContentType: ElementContentType.Number),
        new("hp", elementContentType: ElementContentType.Number),
        new("mp", elementContentType: ElementContentType.Number),
        new("attack", elementContentType: ElementContentType.Number),
        new("defense", elementContentType: ElementContentType.Number),
        new("magic", elementContentType: ElementContentType.Number),
        new("magdef", elementContentType: ElementContentType.Number),
        new("speed", elementContentType: ElementContentType.Number),
        new("dext", elementContentType: ElementContentType.Number),
        new("move", elementContentType: ElementContentType.Number),
        new("hprec", elementContentType: ElementContentType.Number),
        new("mprec", elementContentType: ElementContentType.Number),
        new("summon_max", elementContentType: ElementContentType.Number),
        new("summon_level", elementContentType: ElementContentType.Number),
        new("heal_max", elementContentType: ElementContentType.Number),
        new("attack_max", elementContentType: ElementContentType.Number),
        new("defense_max", elementContentType: ElementContentType.Number),
        new("magic_max", elementContentType: ElementContentType.Number),
        new("magdef_max", elementContentType: ElementContentType.Number),
        new("speed_max", elementContentType: ElementContentType.Number),
        new("dext_max", elementContentType: ElementContentType.Number),
        new("move_max", elementContentType: ElementContentType.Number),
        new("hprec_max", elementContentType: ElementContentType.Number),
        new("mprec_max", elementContentType: ElementContentType.Number),
        new("movetype", elementContentType: ElementContentType.Movetype),
        new("line"),
        new("satellite"),
        new("beast_unit"),
        new("no_knock"),
        new("no_cover"),
        new("view_unit"),
        new("element_lost"),
        new("attack_range", elementContentType: ElementContentType.Number),
        new("escape_range", elementContentType: ElementContentType.Number),
        new("escape_run", elementContentType: ElementContentType.Number),
        new("hand_range", elementContentType: ElementContentType.Number),
        new("wake_range", elementContentType: ElementContentType.Number),
        new("view_range", elementContentType: ElementContentType.Number),
        new("cavalry_range", elementContentType: ElementContentType.Number),
        new("level_max", elementContentType: ElementContentType.Number),
        new("exp_mul", elementContentType: ElementContentType.Number),
        new("exp_max", elementContentType: ElementContentType.Number),
        new("hpUp", elementContentType: ElementContentType.Number),
        new("mpUp", elementContentType: ElementContentType.Number),
        new("attackUp", elementContentType: ElementContentType.Number),
        new("defenseUp", elementContentType: ElementContentType.Number),
        new("magicUp", elementContentType: ElementContentType.Number),
        new("magdefUp", elementContentType: ElementContentType.Number),
        new("speedUp", elementContentType: ElementContentType.Number),
        new("dextUp", elementContentType: ElementContentType.Number),
        new("moveUp", elementContentType: ElementContentType.Number),
        new("hprecUp", elementContentType: ElementContentType.Number),
        new("mprecUp", elementContentType: ElementContentType.Number),
        new("hpMax", elementContentType: ElementContentType.Number),
        new("mpMax", elementContentType: ElementContentType.Number),
        new("attackMax", elementContentType: ElementContentType.Number),
        new("defenseMax", elementContentType: ElementContentType.Number),
        new("magicMax", elementContentType: ElementContentType.Number),
        new("magdefMax", elementContentType: ElementContentType.Number),
        new("speedMax", elementContentType: ElementContentType.Number),
        new("dextMax", elementContentType: ElementContentType.Number),
        new("moveMax", elementContentType: ElementContentType.Number),
        new("hprecMax", elementContentType: ElementContentType.Number),
        new("mprecMax", elementContentType: ElementContentType.Number),
        new("free_move"),
        new("lost_corpse"),
        new("dead_event"),
        new("add_vassal"),
        new("fkey"),
        new("brave", elementContentType: ElementContentType.Number),
        new("change"),
        new("multi"),
        new("item"),
        new("friend"),
        new("friend_ex"),
        new("merce"),
        new("consti"),
        new("member"),
        new("skill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("skill2", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("learn", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("delskill", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("delskill2", elementContentType: ElementContentType.Skill | ElementContentType.Skillset),
        new("value"),
        new("force_voice"),
        new("no_training"),
        new("handle"),
        new("red"),
        new("sub_image"),
        new("sub_image2"),
        new("yorozu"),
        new("rank_text", elementContentType: ElementContentType.Text),
        new("sortkey", elementContentType: ElementContentType.Number),
        new("text", elementContentType: ElementContentType.Text),
        // new("samecall_baseup"),
    };

    internal static readonly ElementInfo[] Power = new ElementInfo[]
    {
        new("castle_battle"),
        new("event"),
        new("name", elementContentType: ElementContentType.Text),
        new("help", elementContentType: ElementContentType.Text),
        new("master", elementContentType: ElementContentType.Unit),
        new("flag"),
        new("bgm"),
        new("volume"),
        new("diplomacy"),
        new("enable_select"),
        new("enable_talent"),
        new("free_raise"),
        new("money", elementContentType: ElementContentType.Number),
        new("home", elementContentType: ElementContentType.Spot),
        new("fix"),
        new("diplo"),
        new("league"),
        new("enemy_power"),
        new("staff"),
        new("merce"),
        new("training_average", elementContentType: ElementContentType.Number),
        new("base_merits"),
        new("merits"),
        new("base_loyal", elementContentType: ElementContentType.Number),
        new("loyals"),
        new("head"),
        new("head2"),
        new("head3"),
        new("head4"),
        new("head5"),
        new("head6"),
        new("diff"),
        new("yabo", elementContentType: ElementContentType.Number),
        new("kosen", elementContentType: ElementContentType.Number),
        new("text", elementContentType: ElementContentType.Text),
        new("member", elementContentType: ElementContentType.Spot),
        new("friend"),
        new("master2"),
        new("master3"),
        new("master4"),
        new("master5"),
        new("master6"),
        new("enable"),
        new("training_up", elementContentType: ElementContentType.Number),
    };

    internal static readonly ElementInfo[] Scenario = new ElementInfo[]
    {
        new("ws_red", elementContentType: ElementContentType.Number),
        new("ws_blue", elementContentType: ElementContentType.Number),
        new("ws_green", elementContentType: ElementContentType.Number),
        new("ws_alpha", elementContentType: ElementContentType.Number),
        new("ws_light", elementContentType: ElementContentType.Number),
        new("ws_light_range", elementContentType: ElementContentType.Number),
        new("discus"),
        new("save_name"),
        new("enable_select"),
        new("max_unit", elementContentType: ElementContentType.Number),
        new("blind"),
        new("name", elementContentType: ElementContentType.Text),
        new("map"),
        new("help", elementContentType: ElementContentType.Text),
        new("locate_x", elementContentType: ElementContentType.Number),
        new("locate_y", elementContentType: ElementContentType.Number),
        new("begin_text", elementContentType: ElementContentType.Text),
        new("world", elementContentType: ElementContentType.Event),
        new("fight", elementContentType: ElementContentType.Event),
        new("politics", elementContentType: ElementContentType.Event),
        new("war_capacity", elementContentType: ElementContentType.Number),
        new("spot_capacity", elementContentType: ElementContentType.Number),
        new("gain_per", elementContentType: ElementContentType.Number),
        new("support_range", elementContentType: ElementContentType.Number),
        new("my_range", elementContentType: ElementContentType.Number),
        new("myhelp_range", elementContentType: ElementContentType.Number),
        new("base_level", elementContentType: ElementContentType.Number),
        new("monster_level", elementContentType: ElementContentType.Number),
        new("training_up", elementContentType: ElementContentType.Number),
        new("actor_per", elementContentType: ElementContentType.Number),
        new("sortkey", elementContentType: ElementContentType.Number),
        new("default_ending"),
        new("power_order"),
        new("enable"),
        new("enable_talent"),
        new("party"),
        new("no_autosave"),
        new("zone"),
        new("nozone"),
        new("item0"),
        new("item1"),
        new("item2"),
        new("item3"),
        new("item4"),
        new("item5"),
        new("item6"),
        new("item_limit"),
        new("poli"),
        new("camp"),
        new("multi"),
        new("item"),
        new("item_sale"),
        new("item_hold"),
        new("text", elementContentType: ElementContentType.Text),
        new("roam", elementContentType: ElementContentType.Unit),
        new("spot", elementContentType: ElementContentType.Spot),
        new("power", elementContentType: ElementContentType.Power),
        new("offset"),
    };

    public static readonly ElementInfo[] Discards = new ElementInfo[] {
        new("str"),
        new("fkey"),
        new("loyal"),
        new("brave"),
        new("arbeit"),
        new("change"),
        new("ground"),
        new("gun_delay"),
        new("text"),
        new("icon"),
        new("wave"),
        new("cutin"),
        new("diplo"),
        new("consti"),
        new("league"),
        new("loyals"),
        new("merits"),
        new("yorozu"),
        new("enemy_power"),
        new("leader_skill"),
        new("assist_skill"),
        new("roam"),
        new("spot"),
        new("power"),
        new("add2"),
        new("item"),
        new("merce"),
        new("next2"),
        new("next3"),
        new("sound"),
        new("member"),
        new("monster"),
        new("item_hold"),
        new("item_sale"),
        new("just_next"),
        new("castle_guard"),
        new("enemy"),
        new("staff"),
        new("friend"),
        new("offset"),
        new("delskill"),
        new("delskill2"),
        new("voice_type"),
        new("ray"),
        new("poli"),
        new("camp"),
        new("home"),
        new("multi"),
        new("learn"),
        new("color"),
        new("joint"),
        new("skill"),
        new("skill2"),
        new("weapon"),
        new("weapon2"),
        new("activenum"),
        new("friend_ex"),
    };
}
